(()=>{'use strict';
const directions=[
{id:46,title:'Warm editorial',origin:'From 28',source:34,note:'The serif from 28, paired with the warmer A from 34. A quiet, flat-lettering comparison against the sculptural treatments.'},
{id:47,title:'Ink & stone',origin:'From 30',source:36,note:'The same serif that made 30 work, paired with the tapered A from 36. This is the restrained monochrome reference.'},
{id:48,title:'Natural stone serif',origin:'30, cut in stone',source:36,note:'Whole carved serif letters with continuous stone surfaces. Natural pits and irregular tool marks replace the repeated texture from round 06.'},
{id:49,title:'Carved sans',origin:'From 32',source:36,note:'A quieter, narrower sans direction inspired by 32, cut from warm weathered stone. Open letters keep the name legible on a small splash.'},
{id:50,title:'Closer set',origin:'Current serif, tighter',source:36,note:'The current serif with tighter optical spacing. It tests whether the wide feeling comes from spacing rather than the letter shapes themselves.'},
{id:51,title:'Narrow editorial',origin:'A different serif',source:36,note:'Bodoni 72 Book offers a distinct, narrower serif silhouette while preserving the proportions of its actual letterforms.'},
{id:52,title:'The sculptor’s letters',origin:'One artist, one rock',source:36,note:'Four individual stone sculptures that clearly read S T I R. Their edges and surfaces feel worked by the same hand as the family A.'},
{id:53,title:'The imperfect cut',origin:'A little less exact',source:36,note:'A more irregular, angular set of hand-cut letters. Small asymmetries test how much character the identity can carry while the name still reads.'}
];
const iconOptions=[{key:'34-none',label:'34 / Statue'},{key:'34-mono',label:'34 / Stone base'},{key:'34-signal',label:'34 / Signal base'},{key:'36-none',label:'36 / Statue'},{key:'36-mono',label:'36 / Stone base'},{key:'36-signal',label:'36 / Signal base'}];
const key='astir-exploration-07';let state={id:48,height:'equal',palette:'mono',theme:'ink',icon:'36-none',shortlist:[],notes:''};let stored=true;
try{const v=JSON.parse(localStorage.getItem(key)||'null');if(v){if(directions.some(d=>d.id===v.id))state.id=v.id;for(const [k,vs]of Object.entries({height:['equal','tall'],palette:['mono','signal','oxide'],theme:['ink','light'],icon:iconOptions.map(i=>i.key)}))if(vs.includes(v[k]))state[k]=v[k];if(Array.isArray(v.shortlist))state.shortlist=[...new Set(v.shortlist.filter(n=>directions.some(d=>d.id===n)))];if(typeof v.notes==='string')state.notes=v.notes}}catch{stored=false}
const $=s=>document.querySelector(s);const path=(id,height=state.height)=>`assets/${id}-${height}-${state.palette}${state.theme==='light'?'-light':''}.png`;
$('#splash-grid').innerHTML=directions.map(d=>`<button class="splash-card" data-direction="${d.id}" aria-pressed="false" aria-label="Inspect ${d.id} ${d.title}"><div class="card-top"><b>${d.id}</b><span>${d.origin}</span><i class="saved-star" aria-hidden="true"></i></div><div class="phone ink"><div class="status"><b>9:41</b><span>▰ ▰ ▰</span></div><div class="island"></div><div class="launch"><img data-preview="${d.id}" src="assets/${d.id}-equal-mono.png" alt="${d.title} on an iPhone splash"><span>OCEAN PARK</span></div><div class="launch-progress"></div><div class="home-line"></div></div><div class="card-name"><strong>${d.title}</strong><small>A from ${d.source} · <span data-height-caption>same height</span></small></div></button>`).join('');
$('#icon-options').innerHTML=iconOptions.map(i=>`<button class="icon-option" data-icon="${i.key}" aria-pressed="false"><img src="assets/icon-${i.key}.png" alt="Black icon ${i.label}"><span>${i.label}</span></button>`).join('');
function persist(){try{localStorage.setItem(key,JSON.stringify(state))}catch{stored=false}$('#storage-status').textContent=stored?'Saved in this browser.':'Download notes to keep them.'}
function render(){const d=directions.find(x=>x.id===state.id);for(const k of ['height','palette','theme'])document.querySelectorAll(`[data-${k}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[k]===state[k])));document.querySelectorAll('[data-direction]').forEach(b=>{b.setAttribute('aria-pressed',String(Number(b.dataset.direction)===state.id));b.querySelector('.saved-star').textContent=state.shortlist.includes(Number(b.dataset.direction))?'★':''});document.querySelectorAll('[data-preview]').forEach(img=>img.src=path(Number(img.dataset.preview)));document.querySelectorAll('.phone,.detail-stage').forEach(el=>{el.classList.toggle('ink',state.theme==='ink');el.classList.toggle('light',state.theme==='light')});document.querySelectorAll('[data-height-caption]').forEach(el=>el.textContent=state.height==='equal'?'same height':'taller statue');document.querySelectorAll('.launch-progress').forEach(el=>el.style.background={mono:state.theme==='ink'?'#BBB8AC':'#454B48',signal:'#F05A3C',oxide:'#A45B42'}[state.palette]);$('#context-note').textContent=state.theme==='ink'?'Ivory stone on ink. One color choice applies to every direction.':'Light contrast study: darker stone and lettering on cool white. Foundation color stays separate.';$('#detail-kicker').textContent=`${d.id} / ${d.title}`;$('#direction-note').textContent=d.note;$('#equal-mark').src=path(d.id,'equal');$('#tall-mark').src=path(d.id,'tall');$('#download-wordmark').href=path(d.id);$('#download-wordmark').download=`Astir-${d.id}-${state.height}-${state.palette}-${state.theme}.png`;$('#download-composition').href='ASTIR-exploration-07.zip';const selected=state.shortlist.includes(d.id);$('#shortlist-button').textContent=`${selected?'★ Shortlisted':'☆ Shortlist'} ${d.id}`;$('#shortlist-button').setAttribute('aria-pressed',String(selected));$('#shortlist-summary').textContent=state.shortlist.length?`Shortlisted: ${[...state.shortlist].sort().join(' · ')}`:'No directions shortlisted yet.';document.querySelectorAll('[data-icon]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.icon===state.icon)));$('#app-icon').src=`assets/icon-${state.icon}.png`;document.querySelectorAll('.selected-app-icon').forEach(img=>img.src=`assets/icon-${state.icon}.png`);document.querySelectorAll('.selected-social').forEach(img=>img.src=`assets/social-${state.icon}.png`);$('#download-app').href=`assets/icon-${state.icon}.png`;for(const platform of ['instagram','tiktok']){$(`#download-${platform}`).href=`assets/social-${state.icon}.png`;$(`#download-${platform}`).download=`Astir-${platform}-${state.icon}.png`}persist()}
for(const k of ['height','palette','theme'])document.querySelectorAll(`[data-${k}]`).forEach(b=>b.onclick=()=>{state[k]=b.dataset[k];render()});document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>{state.id=Number(b.dataset.direction);render()});document.querySelectorAll('[data-icon]').forEach(b=>b.onclick=()=>{state.icon=b.dataset.icon;render()});$('#shortlist-button').onclick=()=>{state.shortlist=state.shortlist.includes(state.id)?state.shortlist.filter(n=>n!==state.id):[...state.shortlist,state.id];render()};$('#notes').value=state.notes;$('#notes').oninput=e=>{state.notes=e.target.value;persist()};$('#download-notes').onclick=()=>{const data={round:'Astir 07',savedAt:new Date().toISOString(),...state,selectedDirection:directions.find(d=>d.id===state.id),references:[28,30,32,34,36]};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Astir-exploration-07-notes.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#storage-status').textContent='Notes downloaded.'};render();
})();
