(()=>{'use strict';
const directions=[
{id:46,title:'The warm reference',origin:'46, preserved',family:'34',description:'The original warm statue and off-white lettering you liked, shown at the chosen taller height. Kept here to judge the new pair against it.'},
{id:54,title:'Original stone, warm type',origin:'36 statue + 46 lettering',family:'36',description:'The statue from 50 keeps its original color. The lettering, warm off-white fill and exact spacing come from 46. This is the mixed-color version.'},
{id:55,title:'Warm stone, warm type',origin:'36 statue, warmed toward 46',family:'36-warm',description:'The same statue shape from 50, with its color warmed toward 46. The lettering and spacing are identical to 54; only the statue’s color treatment changes.'}
];
const families={'34':'34 warm original','36':'36 original','36-warm':'36 warmed'};
const bases=[{key:'long',title:'Full-width base',note:'The broader foundation from the previous icon.'},{key:'compact',title:'Statue-width base',note:'Exactly the width of the statue, with the same depth.'},{key:'none',title:'No base',note:'The uninterrupted A silhouette, kept for comparison.'}];
const key='astir-exploration-08';let state={direction:54,palette:'signal',family:'36',base:'compact',notes:''},storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){if([54,55].includes(saved.direction))state.direction=saved.direction;for(const [k,values]of Object.entries({palette:['signal','oxide'],family:Object.keys(families),base:bases.map(b=>b.key)}))if(values.includes(saved[k]))state[k]=saved[k];if(typeof saved.notes==='string')state.notes=saved.notes}}catch{storageOK=false}
const $=selector=>document.querySelector(selector);
const mark=id=>`assets/${id}-tall-${state.palette}.png`;
const icon=(base=state.base,kind='icon')=>`assets/${kind}-${state.family}-${base==='none'?'none':`${base}-${state.palette}`}.png`;
$('#splash-grid').innerHTML=directions.map(d=>`<article class="splash-card${d.id===46?' reference':''}" data-card="${d.id}"><div class="card-head"><b>${d.id}</b><span>${d.origin}</span>${d.id===46?'<i>Reference</i>':''}</div><div class="phone"><div class="status"><b>9:41</b><span>▰ ▰ ▰</span></div><div class="island"></div><div class="launch"><img data-mark="${d.id}" src="assets/${d.id}-tall-signal.png" alt="${d.title} on an iPhone splash"><span>OCEAN PARK</span></div><div class="progress"></div><div class="home-line"></div></div><div class="card-copy"><h3>${d.title}</h3><p>${d.description}</p>${d.id===46?'<span class="reference-caption">The original stays exactly as saved.</span>':`<button class="choose-direction" data-direction="${d.id}" aria-pressed="false">Inspect ${d.id} + matching icon ↓</button>`}</div></article>`).join('');
$('#base-grid').innerHTML=bases.map(b=>`<button class="base-card" data-base="${b.key}" aria-pressed="false"><div class="base-previews"><img class="square" data-base-square="${b.key}" src="${icon(b.key)}" alt="${b.title} as a square app icon"><img class="circle" data-base-circle="${b.key}" src="${icon(b.key,'social')}" alt="${b.title} as a circular profile picture"></div><div class="base-copy"><b>${b.title}</b><span>${b.note}</span></div><small data-base-selection="${b.key}">Choose this base</small></button>`).join('');
function persist(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true}catch{storageOK=false}$('#storage-status').textContent=storageOK?'Saved in this browser.':'Download your notes to keep them.'}
function render(){const d=directions.find(d=>d.id===state.direction);for(const k of ['palette','family','base','direction'])document.querySelectorAll(`[data-${k}]`).forEach(el=>el.setAttribute('aria-pressed',String(String(state[k])===el.dataset[k])));document.querySelectorAll('[data-card]').forEach(el=>el.classList.toggle('selected',Number(el.dataset.card)===state.direction));document.querySelectorAll('[data-mark]').forEach(img=>img.src=mark(Number(img.dataset.mark)));document.querySelectorAll('.progress').forEach(el=>el.style.background=state.palette==='signal'?'#F05A3C':'#A45B42');$('#selected-kicker').textContent=`${d.id} / ${d.title}`;$('#selected-wordmark').src=mark(d.id);$('#direction-description').textContent=d.description;$('#download-wordmark').href=mark(d.id);$('#download-wordmark').download=`Astir-${d.id}-tall-${state.palette}.png`;document.querySelectorAll('[data-base-square]').forEach(img=>img.src=icon(img.dataset.baseSquare));document.querySelectorAll('[data-base-circle]').forEach(img=>img.src=icon(img.dataset.baseCircle,'social'));document.querySelectorAll('[data-base-selection]').forEach(el=>el.textContent=el.dataset.baseSelection===state.base?'Selected for preview':'Choose this base');$('#app-icon').src=icon();document.querySelectorAll('.selected-app-icon').forEach(img=>img.src=icon());document.querySelectorAll('.selected-social').forEach(img=>img.src=icon(state.base,'social'));$('#download-app').href=icon();$('#download-app').download=`Astir-app-${state.family}-${state.base}${state.base==='none'?'':`-${state.palette}`}.png`;for(const platform of ['instagram','tiktok']){$(`#download-${platform}`).href=icon(state.base,'social');$(`#download-${platform}`).download=`Astir-${platform}-${state.family}-${state.base}${state.base==='none'?'':`-${state.palette}`}.png`}$('#selection-summary').textContent=`${d.id} / ${d.title} · ${state.palette==='signal'?'Signal':'Oxide'} wordmark base · ${families[state.family]} icon · ${bases.find(b=>b.key===state.base).title}`;persist()}
for(const k of ['palette','family','base'])document.querySelectorAll(`[data-${k}]`).forEach(button=>button.onclick=()=>{state[k]=button.dataset[k];render()});document.querySelectorAll('[data-direction]').forEach(button=>button.onclick=()=>{state.direction=Number(button.dataset.direction);state.family=directions.find(d=>d.id===state.direction).family;render()});$('#notes').value=state.notes;$('#notes').oninput=e=>{state.notes=e.target.value;persist()};$('#download-notes').onclick=()=>{const saved={round:'Astir 08',savedAt:new Date().toISOString(),locked:{statueHeight:'tall',lettering:'46 exact glyph paths, spacing and warm fill',wordmarkFoundation:'full width'},...state,selectedWordmark:mark(state.direction),selectedIcon:icon(),selectedProfile:icon(state.base,'social')};const url=URL.createObjectURL(new Blob([JSON.stringify(saved,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Astir-exploration-08-selection.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#storage-status').textContent='Selection and notes downloaded.'};render();
})();
