from pathlib import Path
import hashlib,json,datetime,subprocess,urllib.request
root=Path('/Users/joelipshutz/Documents/ChatGPT/New project/onboarding-copy-review/session-2026-09-16');repo=root.parent.parent/'wander-native-onboarding-review';media=root/'native-captures';m=json.loads((root/'native-finishes.json').read_text());copies=json.loads((root/'native-copy.json').read_text());now=datetime.datetime.now(datetime.timezone.utc).isoformat()
assert m['motionRevision']=='signal-slide-v1' and len(m['finishes'])==1
assert copies['sourceCommit']==m['sourceCommit']
for s in copies['sourceFiles']:assert hashlib.sha256(Path(s['path']).read_bytes()).hexdigest()==s['sha256']
videoProof=[]
for mode,a in m['finishes'][0]['appearances'].items():
 assert hashlib.sha256((root/a['file']).read_bytes()).hexdigest()==a['sha256']
 req=urllib.request.Request('http://127.0.0.1:8766/session-2026-09-16/'+a['file'],headers={'Range':'bytes=0-99'})
 with urllib.request.urlopen(req) as r:assert r.status==206 and len(r.read())==100
 videoProof.append({'appearance':mode,'file':a['file'],'sha256':a['sha256'],'httpRange':206,'accountConfirmed':a['accountConfirmed']})
log=(root/'native-signal-slide-tests.log').read_text();assert '** TEST SUCCEEDED **' in log;assert 'Executed 29 tests, with 0 failures' in log;assert 'Executed 3 tests, with 0 failures' in log
sims=json.loads(subprocess.check_output(['xcrun','simctl','list','devices','--json'],text=True));owned=['3634A858-7A50-4EC3-8C21-56E6B16A6985','7BE74040-8A1F-40AF-994D-7EBDD9E17194'];status={s['udid']:s['state'] for devices in sims['devices'].values() for s in devices if s['udid'] in owned};assert len(status)==2 and all(s=='Shutdown' for s in status.values())
report={'verifiedAt':now,'sourceCommit':m['sourceCommit'],'nativeSwift':True,'treatmentCount':1,'motionRevision':m['motionRevision'],'higgsfieldGenerationUsed':False,'tests':{'welcomeUnit':29,'welcomeUI':3,'failures':0,'result':'native-signal-slide-tests.xcresult'},'sourceFilesVerified':len(copies['sourceFiles']),'videos':videoProof,'compactScreens':6,'directVisualEvidence':['signal-compact.jpg','signal-dark-states.jpg','signal-light-states.jpg','signal-mid-transitions.jpg','signal-scene-transitions.jpg'],'browser':{'playPause':True,'wordReplay':True,'stateSeeking':True,'lightPlaybackImmediatelyAfterSwitch':True,'accountEndState':True,'fullPhoneContain':True,'noCropTransform':True,'noConsoleErrors':True,'noHorizontalOverflow':True,'tvAndNarrowTested':True,'viewportOverrideReset':True,'note':'Existing pinch-zoom coordinate offset affected automation clicks; navigating to the final version restored scale 1. Mouse and keyboard state controls then passed.'},'simulators':status,'unresolved':['Creative acceptance at this launch-blocker checkpoint.','Earlier unrelated place-data performance budgets and broad Map/NUX gates remain outside focused clearance.','Physical-device frame pacing not measured.','Public GitHub and detailed Linear handoff remain behind existing approval gates.'],'deferred':'Events-placeholder style and other-chat context explicitly not investigated; stop here for Joe/Ryan feedback.'}
(root/'native-board-qa/native-signal-slide-report.json').write_text(json.dumps(report,indent=2)+'\n')
summary='''**Current T15 Signal slide checkpoint:** Native source `966866bac8f31fd13429a1aae22c7719c381da9c` replaces the active physical boards with ONE plain-text treatment. COMMUNITY → PEOPLE → PLACES → LOVED ONES uses naturally spaced Avenir Next Bold Signal caps. The external Connect with your remains editorial serif. Whole outgoing/incoming labels slide simultaneously using shared 1.5-second easing; the first word has its own entrance plus a full reading hold. The quick serif fade precedes the three-line A / LOCAL / EXPERIMENT slide. Complete benefit phrases and upper native previews use the same motion. No flap renderer or flap haptics run in the current welcome path; archived physical helpers remain inactive.

The shared-helper build passed **29 welcome unit tests and three native UI journeys**, zero failures (`native-signal-slide-tests.log/.xcresult`). Both complete native light/dark recordings reach account creation. Six compact native screens and full-size settled/mid-transition frames were inspected: exact copy, serif lead, actual park photo, whole-word handoffs, full-scene move and simultaneous benefit UI/text move. The one-player gallery supports play/pause, restart, state seeking, immediate light-mode playback, account-end seeking and TV mode. Normal, wide-TV and narrow layouts have no horizontal overflow; complete phones use contain without cropping. The final version resets the old document’s pinch-zoom offset; mouse and keyboard controls pass. Browser errors: none. Both movies support HTTP206 and match their hashes; all 27 source hashes match. Both owned simulators are shut down. Evidence: `native-board-qa/native-signal-slide-report.json`.

Canonical review: `http://127.0.0.1:8766/session-2026-09-16/opening-explorations.html?v=966866b`. W00–W02, the four-state brief, source inventory and full flowchart are refreshed. Previous physical gallery preserved at `archives/native-finishes-readable/`. T15 exact transcript and the durable checklist are at the top of `TASKS.md`. **Stop at this launch-blocker checkpoint for Joe/Ryan feedback.** Events-placeholder style/context was explicitly deferred and has not been searched or inspected. Separate NUX work remains untouched. No Higgsfield generation or credits used in this pass.

Earlier unrelated place-data performance failures and broad Map/NUX gates remain unresolved; this is scoped creative review, not release clearance. Physical-device frame pacing is not measured. Local code/evidence is ready; existing public GitHub and detailed Linear publication choices remain pending and were not retried. Free space after the final build was 47.6 GiB; a future build must pass the helper’s 50 GiB floor. Do not bypass it or delete unrelated caches.

'''
p=root/'native-verification.md';s=p.read_text();a=s.index('**Current physical/readability revision:**');s=s[:a]+summary+s[a:].replace('**Current physical/readability revision:**','**Previous physical/readability revision:**',1);p.write_text(s)
p=repo/'docs/reviews/rec-529-native-onboarding.md';s=p.read_text();a=s.find('\n\n');s=s[:a+2]+'## September 17 · one Signal slide launch-blocker checkpoint\n\n'+summary+s[a+2:];p.write_text(s)
p=root/'TASKS.md';s=p.read_text().replace('- [ ] Record the one native treatment in dark/light; inspect compact/full-size screens and transitions.','- [x] Both complete native light/dark recordings reach account creation; six compact screens and full-size/mid-transition frames inspected.').replace('- [ ] Replace canonical gallery with the one-treatment launch-blocker checkpoint; archive prior physical gallery and refresh brief/main-board provenance.','- [x] Canonical gallery now contains one native treatment at `?v=966866b`, with exact T15 transcript and state replay controls. Physical gallery archived; W00–W02, four-state brief, full flowchart and provenance refreshed.').replace('- [ ] Validate playback and retain a local handoff. STOP for Joe/Ryan feedback.','- [x] Playback, pause, state/account seeking, light/dark switching, TV/narrow layouts, source/movie hashes and HTTP206 pass. Both simulators shut down. Local handoff saved; STOP for Joe/Ryan feedback. Evidence: `native-board-qa/native-signal-slide-report.json`.');p.write_text(s)
p=media/'media-manifest.json';d=json.loads(p.read_text());entries={x['file']:x for x in d['media']};paths=[media/f'{x}.png' for x in ['W00','W01','W02','W00-compact','opening-state-01','opening-state-02','opening-state-03','opening-state-04']]+list((media/'signal-slide').glob('*.png'))+list((media/'signal-slide').glob('*.mp4'))
for f in paths:entries[str(f.relative_to(media))]={'file':str(f.relative_to(media)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'sourceCommit':m['sourceCommit']}
d['media']=sorted(entries.values(),key=lambda x:x['file']);d['updatedAt']=now;p.write_text(json.dumps(d,indent=2)+'\n')
print('Verified 32 tests, 27 source hashes, 2 video hashes/HTTP206, 6 compact screens; local handoff saved.')
