from pathlib import Path
import hashlib,json,urllib.request,datetime,subprocess
r=Path(__file__).resolve().parents[2];m=json.loads((r/'native-finishes.json').read_text());d=json.loads((r/'native-copy.json').read_text())
for s in d['sourceFiles']:assert hashlib.sha256(Path(s['path']).read_bytes()).hexdigest()==s['sha256']
movies=[]
for mode,a in m['finishes'][0]['appearances'].items():
 assert hashlib.sha256((r/a['file']).read_bytes()).hexdigest()==a['sha256']
 with urllib.request.urlopen(urllib.request.Request('http://127.0.0.1:8766/session-2026-09-16/'+a['file'],headers={'Range':'bytes=0-1023'}),timeout=10) as response:
  assert response.status==206 and len(response.read())==1024
 movies.append({'mode':mode,'file':a['file'],'rangeResponse':206,'sha256':a['sha256']})
report={'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'implementationCommit':m['sourceCommit'],'integrationHead':'18b24196caab381eba1946da4ceeb4466c9a817f','mergeCommit':'ba54c5296ee9601797ee2ce90ee66d1355ca95bd','pr':'https://github.com/joelipshutz/wander/pull/668','tests':{'unit':240,'uiJourneys':4,'failures':0,'log':'native-opening-final-tests.log','result':'native-opening-final-tests.xcresult'},'genericSimulatorBuild':{'result':'passed','log':'native-opening-integration-build.log'},'review':'No remaining code-review findings; final source review completed after accessibility and production-route coverage fixes.','sourceHashesVerified':len(d['sourceFiles']),'movies':movies,'compactScreensVerified':6,'visualInspection':'Heading fits, is slightly larger and closer; orange center preserved. Full native states and account end states verified.','backgroundColor':'Unchanged from 966866b: light .white; dark AstirTheme.ink.color','browser':'Native playback reaches account end; light/dark switching, seeking, pause and full-phone TV layout verified.','xcodeBranchChooser':'Wander, codex/rec-529-opening-signal','manifest':{'workflow':'https://github.com/joelipshutz/wander/actions/runs/35319546169','status':'success','entry':'ba54c5296e / #668 / ship','baseline':'testflight/build-175'},'simulators':'Compact simulator shut down; standard iPhone 17 Pro reopened at user request for hands-on testing, latest integrated build installed, local test auth, opening paused.','scope':'Opening shipped only; remaining NUX and Events preserved for subsequent work.'}
(r/'native-board-qa/native-opening-final-report.json').write_text(json.dumps(report,indent=2)+'\n')
p=r/'TASKS.md';s=p.read_text().replace('- [ ] Fresh native tests/build, full dark/light recordings and compact-screen verification.','- [x] Fresh native verification: 240 unit tests + four UI journeys passed; generic Simulator build passed after merging latest main. Full dark/light recordings and six compact screens verified.').replace('- [ ] Refresh one canonical exploration, brief and opening cards with accurate source provenance.','- [x] Canonical gallery, brief, W00–W02 and source provenance refreshed at `?v=4cba092`. Original NUX source is preserved in the archive worktree; earlier Signal gallery remains usable.').replace('- [ ] Review, focused public PR, CI, squash merge and TestFlight manifest classification. No TestFlight upload or version bump requested. Keep REC-529 open for remaining NUX scope.','- [x] Review, public PR #668 and required CI passed; squash merged as `ba54c5296ee9601797ee2ce90ee66d1355ca95bd`. Main manifest workflow succeeded and issue #342 classifies the exact commit as ship. No TestFlight upload/version bump. Keep REC-529 open for remaining NUX scope.')
needle='Prior NUX captures retain archive source provenance.'
s=s.replace(needle,'Final evidence: `native-board-qa/native-opening-final-report.json`. Source `4cba092`; integration/docs head `18b2419`; Xcode Branch Chooser confirmed `codex/rec-529-opening-signal`. Joe asked about white: source comparison confirms light `.white` and dark Astir Ink are unchanged from `966866b`. Joe then requested a simulator build; latest integrated app installed on the existing iPhone 17 Pro, dark mode, opening paused, local test auth. Leave it open for his testing. Compact simulator is shut down.\n\n'+needle,1)
p.write_text(s)
print('Final evidence saved: 31 source hashes, two HTTP206 videos, 244 tests, generic build, merged PR and classified manifest.')
