import Foundation

extension PlaceCheckInQuestionCatalog {
    static let everydayProfiles: [PlaceCheckInQuestionProfile] = [
        // Shopping
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Store"], questionIDs: ["everyday_browsing", "everyday_staff_help", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Market"], questionIDs: ["everyday_browsing", "everyday_payment", "everyday_shelter"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Shopping mall"], questionIDs: ["everyday_wayfinding", "seating", "restroom"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Department store"], questionIDs: ["everyday_wayfinding", "everyday_fitting", "everyday_staff_help"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["General store"], questionIDs: ["everyday_browsing", "everyday_staff_help", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Convenience store"], questionIDs: ["waiting", "everyday_payment", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Discount store"], questionIDs: ["everyday_browsing", "everyday_prices", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Warehouse store"], questionIDs: ["everyday_loading", "everyday_payment", "everyday_browsing"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Wholesaler"], questionIDs: ["everyday_visitor_access", "everyday_loading", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Grocery store"], questionIDs: ["waiting", "everyday_payment", "everyday_refill"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Supermarket"], questionIDs: ["everyday_browsing", "waiting", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Hypermarket"], questionIDs: ["everyday_wayfinding", "everyday_parking", "everyday_loading"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Food store"], questionIDs: ["everyday_staff_help", "everyday_payment", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Farmers market"], questionIDs: ["everyday_payment", "everyday_shelter", "everyday_rest_seats"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Flea market"], questionIDs: ["everyday_browsing", "everyday_payment", "everyday_rest_seats"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Asian grocery"], questionIDs: ["everyday_staff_help", "everyday_browsing", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Butcher"], questionIDs: ["everyday_staff_help", "waiting", "everyday_pickup"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Health food store"], questionIDs: ["everyday_refill", "everyday_staff_help", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Liquor store"], questionIDs: ["everyday_staff_help", "everyday_prices", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Book store"], questionIDs: ["everyday_browsing", "seating", "everyday_staff_help"]),
        // Specialty shops share practical selection and price questions where
        // the type does not establish a particular service or supply policy.
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Art supply store"], questionIDs: ["everyday_staff_help", "everyday_browsing", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Craft store"], questionIDs: ["everyday_browsing", "everyday_prices", "everyday_staff_help"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Gift shop"], questionIDs: ["everyday_gift_wrap", "everyday_staff_help", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Toy store"], questionIDs: ["everyday_browsing", "everyday_gift_wrap", "everyday_staff_help"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Clothing store"], questionIDs: ["everyday_fitting", "everyday_staff_help", "everyday_browsing"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Women's clothing"], questionIDs: ["everyday_fitting", "everyday_staff_help", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Shoe store"], questionIDs: ["everyday_fitting", "everyday_staff_help", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Jewelry store"], questionIDs: ["everyday_staff_help", "everyday_repair", "everyday_appointment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Cosmetics store", "Cosmetics"], questionIDs: ["everyday_staff_help", "everyday_product_testers", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Beauty supply"], questionIDs: ["everyday_staff_help", "everyday_browsing", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Sporting goods"], questionIDs: ["everyday_staff_help", "everyday_repair", "everyday_fitting"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Sportswear"], questionIDs: ["everyday_fitting", "everyday_staff_help", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Bicycle store"], questionIDs: ["everyday_repair", "everyday_staff_help", "everyday_turnaround"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Electronics"], questionIDs: ["everyday_staff_help", "everyday_repair", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Cell phone store"], questionIDs: ["waiting", "everyday_instructions", "everyday_repair"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Home goods"], questionIDs: ["everyday_browsing", "everyday_loading", "everyday_gift_wrap"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Home improvement"], questionIDs: ["everyday_staff_help", "everyday_loading", "everyday_pickup"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Hardware"], questionIDs: ["everyday_staff_help", "everyday_repair", "everyday_loading"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Building materials"], questionIDs: ["everyday_loading", "everyday_pickup", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Furniture"], questionIDs: ["everyday_browsing", "everyday_loading", "everyday_pickup"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Garden center"], questionIDs: ["everyday_browsing", "everyday_staff_help", "everyday_loading"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Pet store"], questionIDs: ["everyday_staff_help", "everyday_browsing", "dog_access"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Auto parts"], questionIDs: ["everyday_staff_help", "everyday_pickup", "everyday_repair"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Thrift store"], questionIDs: ["everyday_browsing", "everyday_fitting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "shopping", subcategories: ["Discount supermarket"], questionIDs: ["waiting", "everyday_payment", "everyday_prices"]),
        // Rental platforms describe equivalent accommodation; preserve the same practical questions.
        // Stays
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Hotel"], questionIDs: ["everyday_room_noise", "everyday_luggage", "everyday_room_cooling"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Resort"], questionIDs: ["everyday_room_noise", "everyday_breakfast", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Motel"], questionIDs: ["everyday_room_noise", "everyday_parking", "everyday_room_cooling"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Hostel"], questionIDs: ["everyday_privacy", "everyday_lockers", "everyday_kitchen"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Inn"], questionIDs: ["everyday_room_noise", "everyday_breakfast", "everyday_arrival"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Bed & breakfast"], questionIDs: ["everyday_breakfast", "everyday_privacy", "everyday_arrival"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Guest house"], questionIDs: ["everyday_privacy", "everyday_breakfast", "everyday_room_noise"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Private guest room"], questionIDs: ["everyday_privacy", "everyday_kitchen", "everyday_arrival"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Airbnb", "Vrbo"], questionIDs: ["everyday_kitchen", "everyday_arrival", "everyday_room_noise"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Extended stay"], questionIDs: ["everyday_kitchen", "everyday_laundry", "everyday_desk"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Cottage"], questionIDs: ["everyday_kitchen", "everyday_room_cooling", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Cabin"], questionIDs: ["everyday_room_cooling", "everyday_kitchen", "everyday_water"]),
        // Same camping types retain the same defaults across Stays and Outdoors.
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Campground"], questionIDs: ["camp_booking", "camp_toilet", "camp_surface"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["RV park"], questionIDs: ["camp_power", "camp_toilet", "camp_booking"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Farm-stay"], questionIDs: ["everyday_privacy", "everyday_kitchen", "dog_access"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Japanese inn"], questionIDs: ["everyday_privacy", "everyday_breakfast", "everyday_changing"]),
        PlaceCheckInQuestionProfile(categoryID: "stays", subcategories: ["Mobile home park"], questionIDs: ["everyday_laundry", "everyday_parking", "everyday_privacy"]),
        // Hair and nail appointments share the same arrival/payment concerns.
        // Services errands
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Bank"], questionIDs: ["waiting", "everyday_appointment", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["ATM"], questionIDs: ["everyday_cash_withdrawal", "everyday_atm_fee", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Accounting"], questionIDs: ["everyday_appointment", "everyday_quote", "everyday_visit_type"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Insurance"], questionIDs: ["everyday_instructions", "everyday_contact", "everyday_quote"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Real estate"], questionIDs: ["everyday_appointment", "everyday_contact", "everyday_visit_type"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Lawyer"], questionIDs: ["everyday_appointment", "everyday_quote", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Consultant"], questionIDs: ["everyday_appointment", "everyday_quote", "everyday_contact"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Marketing consultant"], questionIDs: ["everyday_quote", "everyday_contact", "everyday_visit_type"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Employment agency"], questionIDs: ["everyday_appointment", "waiting", "everyday_visitor_access"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Nonprofit"], questionIDs: ["everyday_visitor_access", "everyday_contact", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Association"], questionIDs: ["everyday_visitor_access", "everyday_contact", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Florist"], questionIDs: ["everyday_staff_help", "everyday_pickup", "everyday_gift_wrap"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Catering"], questionIDs: ["everyday_quote", "everyday_pickup", "everyday_contact"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Food delivery"], questionIDs: ["everyday_contact", "everyday_prices", "everyday_instructions"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Child care"], questionIDs: ["everyday_visitor_access", "everyday_appointment", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Summer camp"], questionIDs: ["everyday_appointment", "everyday_visitor_guidance", "everyday_dropoff"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Laundry"], questionIDs: ["everyday_self_service", "everyday_machines", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Tailor"], questionIDs: ["everyday_fitting", "everyday_turnaround", "everyday_quote"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Courier"], questionIDs: ["everyday_dropoff", "waiting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Shipping"], questionIDs: ["everyday_dropoff", "everyday_supplies", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Storage"], questionIDs: ["everyday_visitor_access", "everyday_loading", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Moving"], questionIDs: ["everyday_quote", "everyday_schedule", "everyday_contact"]),
        // On-site trades need scheduling and estimates, not collection times.
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Electrician"], questionIDs: ["everyday_quote", "everyday_contact", "everyday_schedule"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Plumber"], questionIDs: ["everyday_quote", "everyday_contact", "everyday_schedule"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Locksmith"], questionIDs: ["everyday_turnaround", "everyday_quote", "everyday_contact"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Painter"], questionIDs: ["everyday_quote", "everyday_contact", "everyday_schedule"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Roofing contractor"], questionIDs: ["everyday_quote", "everyday_schedule", "everyday_visit_type"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["General contractor"], questionIDs: ["everyday_quote", "everyday_appointment", "everyday_schedule"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Pet care"], questionIDs: ["everyday_appointment", "everyday_dropoff", "everyday_quote"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Pet boarding"], questionIDs: ["booking", "everyday_dropoff", "everyday_visitor_guidance"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Funeral home"], questionIDs: ["everyday_visitor_access", "everyday_waiting_space", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Cemetery"], questionIDs: ["everyday_wayfinding", "everyday_rest_seats", "shade"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Astrologer"], questionIDs: ["everyday_appointment", "everyday_prices", "everyday_visit_type"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Psychic"], questionIDs: ["everyday_appointment", "everyday_prices", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Tour agency"], questionIDs: ["booking", "everyday_instructions", "everyday_contact"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Travel agency"], questionIDs: ["everyday_appointment", "everyday_staff_help", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Tourist information"], questionIDs: ["everyday_visitor_guidance", "everyday_staff_help", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Chauffeur"], questionIDs: ["booking", "everyday_contact", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Aircraft rental"], questionIDs: ["booking", "everyday_visitor_guidance", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Telecommunications"], questionIDs: ["waiting", "everyday_appointment", "everyday_visit_type"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Beauty service"], questionIDs: ["everyday_appointment", "everyday_prices", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Skin care clinic"], questionIDs: ["everyday_appointment", "everyday_instructions", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Tanning studio"], questionIDs: ["everyday_appointment", "everyday_changing", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Hair salon"], questionIDs: ["everyday_appointment", "waiting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Barber"], questionIDs: ["waiting", "everyday_appointment", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Nail salon"], questionIDs: ["everyday_appointment", "waiting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Makeup artist"], questionIDs: ["everyday_appointment", "everyday_visit_type", "everyday_supplies"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Body art"], questionIDs: ["everyday_appointment", "everyday_prices", "everyday_visitor_guidance"]),
        PlaceCheckInQuestionProfile(categoryID: "services_errands", subcategories: ["Tattoo/piercing"], questionIDs: ["everyday_appointment", "everyday_quote", "everyday_visitor_guidance"]),
        // Car/truck dealerships share the same visitor and purchase-arrival concerns.
        // Travel transit
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Airport"], questionIDs: ["everyday_wayfinding", "everyday_barrier", "everyday_luggage"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["International airport"], questionIDs: ["everyday_barrier", "everyday_charging", "everyday_showers"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Airstrip"], questionIDs: ["everyday_visitor_access", "everyday_waiting_space", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Heliport"], questionIDs: ["everyday_visitor_access", "everyday_boarding", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Train station"], questionIDs: ["everyday_wayfinding", "everyday_boarding", "restroom"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Subway station"], questionIDs: ["everyday_boarding", "everyday_wayfinding", "everyday_barrier"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Light rail"], questionIDs: ["everyday_boarding", "everyday_shelter", "everyday_instructions"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Tram stop"], questionIDs: ["everyday_shelter", "everyday_boarding", "seating"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Bus stop"], questionIDs: ["everyday_shelter", "seating", "everyday_instructions"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Bus station"], questionIDs: ["everyday_waiting_space", "restroom", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Ferry terminal"], questionIDs: ["everyday_boarding", "everyday_shelter", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Ferry service"], questionIDs: ["everyday_boarding", "seating", "restroom"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Transit station"], questionIDs: ["everyday_wayfinding", "restroom", "everyday_barrier"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Transit stop"], questionIDs: ["everyday_shelter", "seating", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Transit depot"], questionIDs: ["everyday_visitor_access", "everyday_wayfinding", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Taxi stand"], questionIDs: ["everyday_shelter", "waiting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Taxi service"], questionIDs: ["everyday_contact", "waiting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Bike share station"], questionIDs: ["everyday_bike_pickup", "everyday_instructions", "everyday_bike_availability"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Parking"], questionIDs: ["everyday_payment", "everyday_parking_surface", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Parking lot"], questionIDs: ["everyday_payment", "everyday_parking_surface", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Parking garage"], questionIDs: ["everyday_payment", "step_free", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Park & ride"], questionIDs: ["everyday_payment", "everyday_shelter", "everyday_boarding"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Gas station"], questionIDs: ["everyday_payment", "restroom", "everyday_tire_air"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["EV charging"], questionIDs: ["everyday_charger_use", "everyday_charging_setup", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["E-bike charging"], questionIDs: ["everyday_charger_use", "everyday_charging_setup", "everyday_shelter"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Rest stop"], questionIDs: ["restroom", "everyday_rest_seats", "everyday_water"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Truck stop"], questionIDs: ["everyday_showers", "restroom", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Toll station"], questionIDs: ["everyday_payment", "everyday_instructions", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Bridge"], questionIDs: ["everyday_walking_surface", "everyday_pedestrian_route", "shade"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Car dealer"], questionIDs: ["everyday_appointment", "everyday_staff_help", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Car rental"], questionIDs: ["waiting", "everyday_pickup", "everyday_prices"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Car repair"], questionIDs: ["everyday_appointment", "everyday_quote", "everyday_turnaround"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Car wash"], questionIDs: ["everyday_self_service", "waiting", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Tire shop"], questionIDs: ["waiting", "everyday_quote", "everyday_turnaround"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Truck dealer"], questionIDs: ["everyday_appointment", "everyday_parking", "everyday_staff_help"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Transportation service"], questionIDs: ["booking", "everyday_contact", "waiting"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["Dump station"], questionIDs: ["everyday_payment", "everyday_instructions", "everyday_supplies"]),
        PlaceCheckInQuestionProfile(categoryID: "travel_transit", subcategories: ["RV water refill"], questionIDs: ["everyday_water", "everyday_payment", "everyday_instructions"]),
        // Generic and secondary schools use visitor logistics, without collecting student details.
        // Work education
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Co-working space"], questionIDs: ["everyday_day_access", "everyday_quiet_work", "outlets"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Business center"], questionIDs: ["everyday_day_access", "everyday_study_rooms", "wifi"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Corporate office"], questionIDs: ["everyday_visitor_access", "everyday_wayfinding", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Manufacturer"], questionIDs: ["everyday_visitor_access", "everyday_appointment", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Supplier"], questionIDs: ["everyday_visitor_access", "everyday_pickup", "everyday_loading"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Farm"], questionIDs: ["everyday_visitor_access", "everyday_walking_surface", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Ranch"], questionIDs: ["everyday_visitor_guidance", "everyday_walking_surface", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Television studio"], questionIDs: ["everyday_visitor_access", "everyday_bag_check", "everyday_visitor_guidance"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Library"], questionIDs: ["everyday_quiet_work", "everyday_study_rooms", "everyday_printing"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["University"], questionIDs: ["everyday_wayfinding", "everyday_visitor_access", "everyday_rest_seats"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["School"], questionIDs: ["everyday_visitor_access", "everyday_wayfinding", "everyday_appointment"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Preschool"], questionIDs: ["everyday_visitor_access", "everyday_appointment", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Primary school"], questionIDs: ["everyday_visitor_access", "everyday_appointment", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Secondary school"], questionIDs: ["everyday_visitor_access", "everyday_appointment", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Academic department"], questionIDs: ["everyday_wayfinding", "everyday_visitor_access", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Educational institution"], questionIDs: ["everyday_visitor_access", "step_free", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "work_education", subcategories: ["Research institute"], questionIDs: ["everyday_visitor_access", "everyday_appointment", "everyday_bag_check"]),
        // Faith-venue access questions deliberately avoid assumptions about a visitor
        // or a religion; equivalent entry/seating profiles may share questions.
        // Civic faith
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["City hall"], questionIDs: ["everyday_visitor_access", "everyday_wayfinding", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Government office"], questionIDs: ["everyday_appointment", "waiting", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Local government office"], questionIDs: ["everyday_appointment", "waiting", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Courthouse"], questionIDs: ["everyday_bag_check", "everyday_wayfinding", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Embassy"], questionIDs: ["everyday_appointment", "everyday_bag_check", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Post office"], questionIDs: ["waiting", "everyday_dropoff", "everyday_supplies"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Police"], questionIDs: ["everyday_visitor_access", "everyday_wayfinding", "everyday_waiting_space"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Neighborhood police station"], questionIDs: ["everyday_visitor_access", "everyday_waiting_space", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Fire station"], questionIDs: ["everyday_visitor_access", "everyday_visitor_guidance", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Church"], questionIDs: ["everyday_visitor_guidance", "step_free", "seating"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Mosque"], questionIDs: ["everyday_visitor_guidance", "step_free", "seating"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Synagogue"], questionIDs: ["everyday_visitor_access", "everyday_visitor_guidance", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Hindu temple"], questionIDs: ["everyday_visitor_guidance", "everyday_photography", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Buddhist temple"], questionIDs: ["everyday_visitor_guidance", "everyday_photography", "seating"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Shinto shrine"], questionIDs: ["everyday_visitor_guidance", "everyday_walking_surface", "everyday_photography"]),
        PlaceCheckInQuestionProfile(categoryID: "civic_faith", subcategories: ["Place of worship"], questionIDs: ["everyday_visitor_guidance", "everyday_visitor_access", "step_free"]),
        // City, region and country answers describe the person's exploration,
        // never facilities or conditions asserted across the whole territory.
        // Areas addresses
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Apartment building"], questionIDs: ["everyday_wayfinding", "step_free", "everyday_parking"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Apartment complex"], questionIDs: ["everyday_wayfinding", "everyday_parking", "everyday_walking_surface"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Condominium complex"], questionIDs: ["everyday_wayfinding", "step_free", "everyday_walking_surface"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Housing complex"], questionIDs: ["everyday_wayfinding", "everyday_walking_surface", "everyday_rest_seats"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Neighborhood"], questionIDs: ["everyday_getting_around", "everyday_rest_seats", "shade"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Locality/city"], questionIDs: ["everyday_getting_around", "everyday_area_highlight", "everyday_area_pace"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Postal area"], questionIDs: ["everyday_getting_around", "everyday_wayfinding", "everyday_area_pace"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Town"], questionIDs: ["everyday_getting_around", "everyday_area_highlight", "everyday_rest_seats"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Region"], questionIDs: ["everyday_getting_around", "everyday_area_pace", "everyday_area_highlight"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Country"], questionIDs: ["everyday_area_highlight", "everyday_getting_around", "everyday_area_pace"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Route/street"], questionIDs: ["everyday_walking_surface", "everyday_rest_seats", "shade"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Address"], questionIDs: ["everyday_wayfinding", "step_free", "everyday_walking_surface"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Intersection"], questionIDs: ["everyday_crossing", "everyday_walking_surface", "everyday_wayfinding"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Landmark"], questionIDs: ["everyday_wayfinding", "everyday_rest_seats", "everyday_area_pace"]),
        PlaceCheckInQuestionProfile(categoryID: "areas_addresses", subcategories: ["Plus code"], questionIDs: ["everyday_wayfinding", "everyday_getting_around", "everyday_walking_surface"]),
        // Facilities other
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Public bathroom"], questionIDs: ["everyday_restroom_fee", "everyday_handwashing", "step_free"]),
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Public bath"], questionIDs: ["everyday_changing", "everyday_lockers", "everyday_showers"]),
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Restroom"], questionIDs: ["everyday_restroom_fee", "everyday_handwashing", "everyday_baby_changing"]),
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Stable"], questionIDs: ["booking", "everyday_horse_equipment", "everyday_visitor_guidance"]),
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Generic establishment"], questionIDs: ["everyday_visitor_access", "step_free", "everyday_payment"]),
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Point of interest"], questionIDs: ["everyday_wayfinding", "seating", "everyday_area_pace"]),
        PlaceCheckInQuestionProfile(categoryID: "facilities_other", subcategories: ["Unknown"], questionIDs: ["everyday_wayfinding", "everyday_visitor_access", "step_free"]),
    ]
}
