import Foundation

extension PlaceCheckInQuestionCatalog {
    /// Each row is a deliberate subtype selection. Shared cuisine rows reflect
    /// equivalent practical dining needs, not assumed dishes or national traits.
    /// Specialized formats below get their own questions when the format itself
    /// gives us reliable context. A nationality never implies spice or a diet.
    static let coreProfiles: [PlaceCheckInQuestionProfile] = [
        p("restaurants_food", "Restaurant", "dog_access outdoor_seating booking_policy"),
        p("restaurants_food", "Thai", "dog_access spice vegetarian"),
        p("restaurants_food", "Vietnamese", "dog_access vegetarian takeaway"),
        p("restaurants_food", "Chinese", "dog_access sharing group_tables"),
        p("restaurants_food", "Korean", "dog_access sharing vegetarian"),
        p("restaurants_food", "Japanese", "dog_access counter_seating vegetarian"),
        p("restaurants_food", "Indian", "dog_access spice vegetarian"),
        p("restaurants_food", "Asian fusion", "dog_access outdoor_seating vegetarian"),
        p("restaurants_food", "Sushi", "dog_access counter_seating booking_policy"),
        p("restaurants_food", "Ramen", "dog_access vegetarian waiting"),
        p("restaurants_food", "Dumplings", "dog_access vegetarian takeaway"),
        p("restaurants_food", "Bao buns", "dog_access vegetarian seating"),
        p("restaurants_food", "Noodles", "dog_access vegetarian portions"),
        p("restaurants_food", "Dim sum", "dog_access sharing waiting"),
        p("restaurants_food", "Hot pot", "table_cooking ventilation vegetarian"),
        p("restaurants_food", "Cantonese", "dog_access sharing group_tables"),
        p("restaurants_food", "Taiwanese", "dog_access vegetarian takeaway"),
        p("restaurants_food", "Izakaya", "dog_access noise booking_policy"),
        p("restaurants_food", "Yakitori", "dog_access counter_seating ventilation"),
        p("restaurants_food", "Yakiniku", "table_cooking ventilation booking_policy"),
        p("restaurants_food", "North Indian|South Indian", "dog_access spice vegetarian"),
        // Broad cuisine labels cannot tell us the actual menu. These rows keep
        // the same answerable choices instead of inventing regional dishes.
        p("restaurants_food", "Pakistani|Sri Lankan|Bangladeshi|Nepalese", "dog_access sharing vegetarian"),
        p("restaurants_food", "Malaysian|Singaporean|Indonesian|Filipino|Burmese|Cambodian|Laotian|Asian", "dog_access dietary_menu portions"),
        p("restaurants_food", "Tibetan|Mongolian|Georgian|Armenian|Uzbek", "dog_access sharing vegetarian"),
        p("restaurants_food", "Mongolian BBQ", "table_cooking service dietary_menu"),
        p("restaurants_food", "Korean BBQ", "table_cooking ventilation group_tables"),
        // Japanese BBQ and Yakiniku are equivalent dining formats.
        p("restaurants_food", "Japanese BBQ", "table_cooking ventilation booking_policy"),
        p("restaurants_food", "Japanese curry", "dog_access spice counter_seating"),
        p("restaurants_food", "Tonkatsu", "dog_access waiting counter_seating"),
        p("restaurants_food", "Afghan|Middle Eastern|Lebanese|Persian|Turkish|Israeli|Palestinian|Syrian|Iraqi|Jordanian|Yemeni", "dog_access sharing vegetarian"),
        p("restaurants_food", "Egyptian|Moroccan|Tunisian|Algerian", "dog_access sharing vegetarian"),
        p("restaurants_food", "Ethiopian|Eritrean", "dog_access sharing vegetarian"),
        p("restaurants_food", "Somali|Kenyan|Nigerian|Ghanaian|Senegalese|South African|African", "dog_access portions vegetarian"),
        p("restaurants_food", "Falafel", "dog_access vegan takeaway"),
        p("restaurants_food", "Gyro", "dog_access takeaway seating"),
        p("restaurants_food", "Kebab", "dog_access portions takeaway"),
        p("restaurants_food", "Shawarma", "dog_access service takeaway"),
        p("restaurants_food", "Halal", "dog_access halal_menu group_tables"),
        p("restaurants_food", "Italian", "dog_access wine_by_glass booking_policy"),
        p("restaurants_food", "Mediterranean", "dog_access vegetarian outdoor_seating"),
        p("restaurants_food", "Greek", "dog_access vegetarian outdoor_seating"),
        p("restaurants_food", "French", "dog_access booking_ease noise"),
        p("restaurants_food", "Spanish", "dog_access sharing wine_by_glass"),
        p("restaurants_food", "Tapas", "dog_access sharing counter_seating"),
        p("restaurants_food", "Portuguese|Basque", "dog_access dietary_menu booking_policy"),
        p("restaurants_food", "German|Austrian|Bavarian|Swiss", "dog_access vegetarian group_tables"),
        p("restaurants_food", "Dutch|Belgian", "dog_access lunch vegetarian"),
        p("restaurants_food", "British|Irish", "dog_access lunch noise"),
        p("restaurants_food", "Scandinavian|Swedish|Norwegian|Finnish|Danish", "dog_access booking_policy vegetarian"),
        p("restaurants_food", "Polish|Ukrainian|Russian|Czech|Slovak|Hungarian|Romanian|Croatian|Serbian|Bosnian|Bulgarian|Albanian|Slovenian|Lithuanian|European|Eastern European", "dog_access portions vegetarian"),
        p("restaurants_food", "Pizza", "dog_access pizza outdoor_seating"),
        p("restaurants_food", "Fish & chips", "dog_access takeaway seating"),
        p("restaurants_food", "Fondue", "dog_access sharing booking_policy"),
        p("restaurants_food", "American|Canadian", "dog_access vegetarian group_tables"),
        p("restaurants_food", "Mexican", "dog_access spice vegetarian"),
        p("restaurants_food", "Tex-Mex", "dog_access portions vegetarian"),
        p("restaurants_food", "Caribbean|Jamaican|Puerto Rican|Dominican|Haitian|Panamanian|Cuban", "dog_access portions takeaway"),
        p("restaurants_food", "Brazilian|Argentinian|Colombian|Chilean|Peruvian|Venezuelan|Ecuadorian|Bolivian|Uruguayan|Salvadoran|Guatemalan|South American|Latin American", "dog_access sharing vegetarian"),
        p("restaurants_food", "Southwestern|Cajun", "dog_access spice vegetarian"),
        p("restaurants_food", "Californian", "dog_access dietary_menu outdoor_seating"),
        p("restaurants_food", "Hawaiian", "dog_access portions takeaway"),
        p("restaurants_food", "Poke", "dog_access dietary_menu takeaway"),
        p("restaurants_food", "Australian|New Zealand|Fijian|Samoan|Tongan", "dog_access sharing portions"),
        p("restaurants_food", "Burgers", "dog_access vegetarian outdoor_seating"),
        p("restaurants_food", "Diner", "dog_access breakfast counter_seating"),
        p("restaurants_food", "Hot dogs", "dog_access takeaway seating"),
        p("restaurants_food", "Barbecue", "dog_access sharing outdoor_seating"),
        p("restaurants_food", "Wings", "dog_access spice group_tables"),
        p("restaurants_food", "Steakhouse", "dog_access booking_policy wine_by_glass"),
        p("restaurants_food", "Bar & grill", "dog_access screens outdoor_seating"),
        p("restaurants_food", "Taco stand", "dog_access takeaway seating"),
        p("restaurants_food", "Taco truck", "dog_access waiting seating"),
        p("restaurants_food", "Burrito", "dog_access vegetarian takeaway"),
        p("restaurants_food", "Taco", "dog_access vegetarian seating"),
        p("restaurants_food", "Sandwich", "dog_access waiting takeaway"),
        p("restaurants_food", "Bagel", "dog_access waiting seating"),
        p("restaurants_food", "Deli", "dog_access service lunch"),
        p("restaurants_food", "Salad", "dog_access dietary_menu portions"),
        p("restaurants_food", "Bistro", "dog_access lunch noise"),
        p("restaurants_food", "Food court", "dog_access seating dietary_menu"),
        p("restaurants_food", "Breakfast", "dog_access breakfast waiting"),
        p("restaurants_food", "Brunch", "dog_access waiting booking_policy"),
        p("restaurants_food", "Soup", "dog_access vegetarian takeaway"),
        p("restaurants_food", "Chicken", "dog_access sharing portions"),
        p("restaurants_food", "Seafood", "dog_access booking_policy outdoor_seating"),
        p("restaurants_food", "Oyster bar", "dog_access counter_seating wine_by_glass"),
        p("restaurants_food", "Vegetarian", "dog_access vegan outdoor_seating"),
        p("restaurants_food", "Vegan", "dog_access dietary_menu outdoor_seating"),
        p("restaurants_food", "Gluten-free", "dog_access gluten_menu outdoor_seating"),
        p("restaurants_food", "Snack bar", "dog_access seating service"),
        p("restaurants_food", "Gastropub", "dog_access beer_selection noise"),

        p("coffee_tea_sweets", "Coffee shop", "laptop outlets dog_access"),
        p("coffee_tea_sweets", "Cafe", "laptop outdoor_seating dog_access"),
        p("coffee_tea_sweets", "Coffee stand", "waiting milk dog_access"),
        p("coffee_tea_sweets", "Coffee lounge", "laptop outlets dog_access"),
        p("coffee_tea_sweets", "Roastery", "beans tasting dog_access"),
        p("coffee_tea_sweets", "Tea house", "noise outdoor_seating dog_access"),
        p("coffee_tea_sweets", "Tea store", "tasting gift_packaging dog_access"),
        p("coffee_tea_sweets", "Juice shop", "juice dog_access waiting"),
        p("coffee_tea_sweets", "Smoothie shop", "milk dog_access waiting"),
        p("coffee_tea_sweets", "Acai", "dietary_menu dog_access seating"),
        p("coffee_tea_sweets", "Bakery", "dog_access dietary_menu seating"),
        p("coffee_tea_sweets", "Bagel shop", "dog_access seating waiting"),
        p("coffee_tea_sweets", "Donut shop", "dog_access waiting dietary_menu"),
        p("coffee_tea_sweets", "Cake shop", "dog_access gift_packaging everyday_staff_help"),
        p("coffee_tea_sweets", "Pastry shop", "dog_access seating dietary_menu"),
        p("coffee_tea_sweets", "Dessert shop", "dog_access takeaway dietary_menu"),
        p("coffee_tea_sweets", "Dessert restaurant", "dog_access sharing booking_ease"),
        // Gelato and ice cream need the same dog-access, dietary and seating facts.
        p("coffee_tea_sweets", "Ice cream|Gelato", "dog_access frozen_treat seating"),
        p("coffee_tea_sweets", "Candy store", "dog_access tasting gift_packaging"),
        p("coffee_tea_sweets", "Chocolate shop", "dog_access tasting gift_packaging"),
        p("coffee_tea_sweets", "Chocolate factory", "guided_tour tasting dog_access"),
        p("coffee_tea_sweets", "Chocolate lounge", "tasting seating dog_access"),
        // Broad confectionery names do not establish whether baked goods exist.
        p("coffee_tea_sweets", "Confectionery", "dog_access tasting gift_packaging"),
        p("coffee_tea_sweets", "Cat cafe", "resident_animals booking_ease seating"),
        p("coffee_tea_sweets", "Dog cafe", "dog_access outdoor_seating resident_animals"),

        p("bars_nightlife", "Bar", "noise alcohol_free dog_access"),
        p("bars_nightlife", "Cocktail bar", "cocktails alcohol_free booking_ease"),
        p("bars_nightlife", "Pub", "dog_access food_at_bar noise"),
        p("bars_nightlife", "Irish pub", "live_music food_at_bar dog_access"),
        p("bars_nightlife", "Billiards", "games game_payment noise"),
        p("bars_nightlife", "Sports bar", "screens booking_ease food_at_bar"),
        p("bars_nightlife", "Wine bar", "wine_by_glass dog_access noise"),
        p("bars_nightlife", "Cider bar", "cider noise food_at_bar"),
        p("bars_nightlife", "Sake bar", "sake food_at_bar noise"),
        p("bars_nightlife", "Game bar", "games game_payment alcohol_free"),
        p("bars_nightlife", "Gastropub", "dog_access beer_selection noise"),
        p("bars_nightlife", "Bar & grill", "dog_access screens outdoor_seating"),
        p("bars_nightlife", "Dance hall", "dancing live_music coat_storage"),
        // Club/nightclub/disco describe the same entry, dance and belongings needs.
        p("bars_nightlife", "Club|Disco|Nightclub", "door dancing coat_storage"),
        p("bars_nightlife", "Lounge", "noise booking_ease cocktails"),
        p("bars_nightlife", "Hookah bar", "smoking_area ventilation alcohol_free"),
        p("bars_nightlife", "Beer garden", "outdoor_seating shade dog_access"),
        p("bars_nightlife", "Jazz club", "show_seating acoustics door"),
        p("bars_nightlife", "Hi-fi lounge", "acoustics noise booking_ease"),
        p("bars_nightlife", "Brewery", "beer_selection tasting dog_access"),
        p("bars_nightlife", "Brewpub", "beer_selection food_at_bar dog_access"),
        p("bars_nightlife", "Winery", "tasting booking_ease dog_access"),
        p("bars_nightlife", "Vineyard", "vineyard tasting dog_access"),
        p("bars_nightlife", "Karaoke", "karaoke booking_ease noise"),
        p("bars_nightlife", "Live music", "acoustics show_seating door"),
        p("bars_nightlife", "Comedy club", "show_seating sightlines door"),
        p("bars_nightlife", "Casino", "smoking_area food_at_bar coat_storage"),
        p("bars_nightlife", "Distillery", "distillery tasting booking_ease"),

        p("outdoors_nature", "Park", "leash shade restroom"),
        p("outdoors_nature", "City park", "leash shade seating"),
        p("outdoors_nature", "State park", "leash restroom admission"),
        p("outdoors_nature", "National park", "leash visitor_info admission"),
        p("outdoors_nature", "Hiking area", "leash incline trail_marking"),
        // A hike and a trail both describe the route underfoot.
        p("outdoors_nature", "Trail|Hike", "leash incline trail_marking"),
        p("outdoors_nature", "Beach", "leash shade beach_rinse"),
        p("outdoors_nature", "Dog beach", "leash beach_rinse beach_access"),
        p("outdoors_nature", "Lake", "leash shade restroom"),
        p("outdoors_nature", "River", "leash water_edge shade"),
        p("outdoors_nature", "Island", "leash shelter ferry_access"),
        p("outdoors_nature", "Woods/forest", "leash trail_marking path_surface"),
        p("outdoors_nature", "Mountain peak", "leash incline shelter"),
        p("outdoors_nature", "Scenic spot", "leash view_access shade"),
        // Viewpoint and overlook are alternative names for the same viewing stop.
        p("outdoors_nature", "Viewpoint|Overlook", "leash view_access seating"),
        p("outdoors_nature", "Waterfall", "leash view_access incline"),
        p("outdoors_nature", "Hot spring", "leash hot_spring changing"),
        p("outdoors_nature", "Cave", "leash cave booking_policy"),
        p("outdoors_nature", "Nature preserve", "leash trail_marking wildlife_viewing"),
        p("outdoors_nature", "Wildlife refuge", "leash path_surface shade"),
        p("outdoors_nature", "Wildlife park", "leash animal_paths admission"),
        p("outdoors_nature", "Botanical garden", "leash path_surface shade"),
        p("outdoors_nature", "Garden", "leash shade seating"),
        p("outdoors_nature", "Picnic area", "leash shade picnic"),
        p("outdoors_nature", "Dog park", "fenced leash water_refill"),
        p("outdoors_nature", "Playground", "playground_age fenced shade"),
        p("outdoors_nature", "Campground", "leash camp_toilet camp_booking"),
        p("outdoors_nature", "RV park", "leash camp_power camp_toilet"),
        p("outdoors_nature", "Dispersed camping", "leash camp_toilet offroad"),
        // Accommodation questions stay consistent when the same type is saved
        // under Outdoors or Stays; no public-bathroom claim for a private cabin.
        p("outdoors_nature", "Cabin", "dog_access everyday_kitchen everyday_room_cooling"),
        p("outdoors_nature", "Cottage", "dog_access everyday_kitchen everyday_parking"),
        p("outdoors_nature", "Marina", "leash restroom arrival_parking"),
        p("outdoors_nature", "Fishing pier", "leash seating shade"),
        p("outdoors_nature", "Fishing pond", "leash fishing_gear shade"),
        p("outdoors_nature", "Fishing charter", "fishing_gear restroom booking_ease"),
        p("outdoors_nature", "Ski resort", "leash ski_rental ski_levels"),
        p("outdoors_nature", "Cycling park", "leash bike_trails water_refill"),
        p("outdoors_nature", "Skate park", "leash skate_features activity_lights"),
        p("outdoors_nature", "Off-roading area", "leash offroad shelter"),
        p("outdoors_nature", "Adventure sports", "adventure_guidance equipment booking_ease"),

        p("things_to_do", "Tourist attraction", "admission visit_time step_free"),
        p("things_to_do", "Landmark", "interpretation view_access visit_time"),
        // Historical place/landmark differ in naming, not visitor logistics.
        p("things_to_do", "Historical place|Historical landmark", "interpretation guided_tour step_free"),
        p("things_to_do", "Monument", "interpretation view_access seating"),
        p("things_to_do", "Sculpture", "interpretation photography step_free"),
        p("things_to_do", "Fountain", "seating shade photography"),
        p("things_to_do", "Castle", "guided_tour incline admission"),
        p("things_to_do", "Plaza|Town square", "seating shade restroom"),
        p("things_to_do", "Visitor center", "visitor_info restroom step_free"),
        p("things_to_do", "Museum", "exhibits visit_time admission"),
        p("things_to_do", "Art museum", "exhibits photography seating"),
        p("things_to_do", "History museum", "interpretation guided_tour visit_time"),
        p("things_to_do", "Art gallery", "exhibits photography admission"),
        p("things_to_do", "Art studio", "art_classes equipment booking"),
        p("things_to_do", "Cultural landmark", "interpretation guided_tour photography"),
        p("things_to_do", "Cultural center", "art_classes visitor_info admission"),
        p("things_to_do", "Theater|Performing arts theater", "sightlines show_seating step_free"),
        p("things_to_do", "Concert hall|Philharmonic hall", "acoustics show_seating coat_storage"),
        p("things_to_do", "Opera house", "sightlines acoustics coat_storage"),
        p("things_to_do", "Amphitheater", "sightlines shade show_seating"),
        p("things_to_do", "Auditorium", "acoustics sightlines step_free"),
        p("things_to_do", "Movie theater", "screen_comfort sightlines cinema_snacks"),
        p("things_to_do", "Planetarium", "show_seating admission visit_time"),
        p("things_to_do", "Observation deck", "view_indoor waiting view_access"),
        p("things_to_do", "Aquarium", "hands_on animal_paths admission"),
        p("things_to_do", "Zoo", "animal_paths shade restroom"),
        p("things_to_do", "Amusement park", "ride_queues ride_storage ride_restrictions"),
        p("things_to_do", "Water park", "ride_storage changing ride_restrictions"),
        p("things_to_do", "Ferris wheel", "ride_queues ride_cabin admission"),
        p("things_to_do", "Roller coaster", "ride_queues ride_storage ride_restrictions"),
        p("things_to_do", "Arcade", "game_payment games noise"),
        p("things_to_do", "Bowling", "booking equipment game_payment"),
        p("things_to_do", "Mini golf", "game_payment shade equipment"),
        p("things_to_do", "Billiards", "games game_payment equipment"),
        p("things_to_do", "Darts", "equipment games group_tables"),
        p("things_to_do", "Axe throwing", "instruction equipment booking"),
        p("things_to_do", "Board game lounge", "board_games game_payment food_at_bar"),
        p("things_to_do", "Go-karting", "ride_restrictions equipment ride_queues"),
        p("things_to_do", "Paintball", "equipment instruction changing"),
        p("things_to_do", "Indoor playground", "indoor_play seating restroom"),
        p("things_to_do", "Event venue", "event_layout event_food step_free"),
        p("things_to_do", "Convention center", "everyday_wayfinding everyday_charging step_free"),
        p("things_to_do", "Banquet hall", "event_food group_tables step_free"),
        p("things_to_do", "Wedding venue", "event_layout event_food outdoor_seating"),
        p("things_to_do", "Community center", "visitor_info event_layout step_free"),
        p("things_to_do", "Internet cafe", "wifi outlets noise"),
        p("things_to_do", "Dance hall", "dancing group_instruction changing"),
        p("things_to_do", "Barbecue area", "barbecue_setup picnic shade"),

        p("wellness_fitness", "Gym", "fitness_dropin gym_equipment changing"),
        // Provider "fitness center" does not establish that classes exist.
        // Treat this broad label as equivalent to Gym, not a coached studio.
        p("wellness_fitness", "Fitness center", "fitness_dropin gym_equipment changing"),
        p("wellness_fitness", "Yoga studio", "yoga_style class_busyness booking_ease"),
        p("wellness_fitness", "Pilates studio", "pilates_reformer class_busyness booking_ease"),
        p("wellness_fitness", "CrossFit gym", "crossfit_scaling crossfit_format fitness_dropin"),
        p("wellness_fitness", "Functional fitness studio", "functional_format coaching venue_busyness"),
        p("wellness_fitness", "Wellness studio", "booking_ease equipment changing_privacy"),
        p("wellness_fitness", "Wellness center", "treatment_booking changing_privacy step_free"),
        p("wellness_fitness", "Sports club", "fitness_dropin court_booking changing"),
        p("wellness_fitness", "Sports complex", "court_booking changing visitor_info"),
        p("wellness_fitness", "Sports coaching", "coaching group_instruction equipment"),
        p("wellness_fitness", "Sports school", "group_instruction instruction equipment"),
        p("wellness_fitness", "Athletic field", "field_surface activity_lights restroom"),
        p("wellness_fitness", "Swimming pool", "pool_use pool_setting changing"),
        p("wellness_fitness", "Tennis court", "tennis_surface court_booking court_lights"),
        p("wellness_fitness", "Golf course", "golf golf_hire booking"),
        p("wellness_fitness", "Indoor golf", "golf_simulator golf_hire booking"),
        p("wellness_fitness", "Ice skating rink", "ice_sessions equipment ride_storage"),
        p("wellness_fitness", "Volleyball court", "volleyball_surface volleyball_net court_booking"),
        p("wellness_fitness", "Soccer field", "field_surface field_goals activity_lights"),
        p("wellness_fitness", "Basketball court", "basketball court_booking court_lights"),
        p("wellness_fitness", "Pickleball court", "pickleball_lines court_booking court_lights"),
        p("wellness_fitness", "Spa", "treatment_booking changing_privacy sauna"),
        p("wellness_fitness", "Massage", "massage privacy treatment_booking"),
        p("wellness_fitness", "Massage spa", "massage changing_privacy treatment_booking"),
        p("wellness_fitness", "Sauna", "sauna changing_privacy booking"),
        p("wellness_fitness", "Chiropractor", "treatment_booking treatment_info privacy"),
        // Care questions cover facility logistics only; never diagnoses, medical
        // effectiveness or a person's reason for visiting. Equivalent care
        // labels intentionally share practical arrival/appointment questions.
        p("wellness_fitness", "Dentist|Dental clinic", "treatment_booking treatment_info step_free"),
        p("wellness_fitness", "Optometrist", "eye_shop treatment_booking step_free"),
        p("wellness_fitness", "Ophthalmologist", "treatment_booking treatment_info step_free"),
        p("wellness_fitness", "Eye care center", "eye_shop treatment_booking waiting"),
        p("wellness_fitness", "Doctor|Dermatologist", "treatment_booking privacy step_free"),
        p("wellness_fitness", "Pediatrician", "waiting everyday_baby_changing step_free"),
        p("wellness_fitness", "Urgent care", "waiting treatment_booking arrival_parking"),
        p("wellness_fitness", "Medical clinic", "treatment_booking waiting step_free"),
        p("wellness_fitness", "Medical center", "visitor_info arrival_parking step_free"),
        p("wellness_fitness", "Hospital", "visitor_info arrival_parking restroom"),
        p("wellness_fitness", "Medical lab", "lab_booking treatment_info waiting"),
        p("wellness_fitness", "Pharmacy|Drugstore", "pharmacy waiting step_free"),
        p("wellness_fitness", "Physiotherapist|Physical therapy", "rehab_space privacy step_free"),
        p("wellness_fitness", "Foot care|Podiatrist", "treatment_booking privacy step_free"),
        p("wellness_fitness", "Veterinary care", "vet_wait treatment_booking arrival_parking"),
        p("wellness_fitness", "Mental health/therapy", "privacy treatment_booking step_free"),
        p("wellness_fitness", "Retreat", "retreat dietary_menu step_free"),

        p("outdoors_nature", "Surf", "surf_rental venue_busyness leash"),
        p("outdoors_nature", "Surf break", "surf_crowding beach_rinse leash"),
        p("outdoors_nature", "Kayak/canoe rental", "equipment booking_ease dogs_on_boats"),
        p("things_to_do", "Stadium", "seat_cover show_seating everyday_bag_check"),
        p("things_to_do", "Arena", "acoustics show_seating everyday_bag_check"),
        p("wellness_fitness", "Beach tennis", "court_booking equipment court_lights"),
        p("wellness_fitness", "Beach volleyball", "volleyball_net court_booking shade"),
        p("wellness_fitness", "Padel court", "court_booking court_setting equipment"),
        p("wellness_fitness", "Climbing gym", "climbing_type equipment venue_busyness"),
        p("wellness_fitness", "Surf school", "equipment class_busyness booking_ease"),

        p("place", "Place", "step_free seating restroom")
    ]

    private static func p(_ category: String, _ subtypes: String, _ questions: String) -> PlaceCheckInQuestionProfile {
        PlaceCheckInQuestionProfile(
            categoryID: category,
            subcategories: subtypes.components(separatedBy: "|"),
            questionIDs: questions.components(separatedBy: " ")
        )
    }
}
