import Foundation

extension PlaceCheckInQuestionCatalog {
    static let coreQuestions: [PlaceCheckInQuestion] = [
        q("booking", "Arranging the visit", "How did you arrange this visit?", "Walked in|Booked ahead|Joined a waitlist", ["Walked in": ["walk in visit"], "Booked ahead": ["booked visit"], "Joined a waitlist": ["waitlist on visit"]]),
        q("booking_policy", "Booking guidance", "What booking guidance did staff or signs give?", "Walk-ins welcome|Booking recommended|Booking required", ["Walk-ins welcome": ["walk ins welcome"], "Booking recommended": ["booking recommended"], "Booking required": ["booking required"]]),
        q("waiting", "Wait", "How long did you wait?", "Under 10 minutes|10–30 minutes|Over 30 minutes", ["Under 10 minutes": ["short wait"]]),
        q("step_free", "Entrance", "Was there a step-free way in?", "Step-free entrance|Ramp available|Steps required", ["Step-free entrance": ["step free entrance"], "Ramp available": ["entrance ramp"]]),
        q("restroom", "Bathroom", "What bathroom access did you find?", "Public access|Customers only|None found", ["Public access": ["public bathroom", "public restroom"], "Customers only": ["customer bathroom"]]),
        q("seating", "Seating", "Somewhere to sit?", "Plenty of seats|A few seats|None found", ["Plenty of seats": ["seating", "seats"], "A few seats": ["seating", "seats"]]),
        q("noise", "Conversation", "How easy was it to talk?", "Easy to talk|Some noise|Hard to hear", ["Easy to talk": ["conversation", "easy to talk"]]),
        q("outdoor_seating", "Outdoor seating", "What outdoor seating was there?", "Covered|Uncovered|Both|None found", ["Covered": ["covered outdoor seating"], "Uncovered": ["outdoor seating"], "Both": ["covered outdoor seating", "outdoor seating"]]),
        q("outlets", "Outlets", "Could you plug in?", "Plenty|A few|None found", ["Plenty": ["outlets", "power outlets"], "A few": ["outlets", "power outlets"]]),
        q("wifi", "Wi-Fi", "How did the Wi-Fi work?", "Worked well|Unreliable|Unavailable", ["Worked well": ["wifi", "reliable wifi"]]),
        q("dog_access", "Dogs", "Where were pet dogs allowed?", "Inside and outside|Inside only|Outside only|Not allowed", ["Inside and outside": ["dogs inside", "dogs indoors", "dogs outside", "dog friendly"], "Inside only": ["dogs inside", "dogs indoors"], "Outside only": ["dogs outside", "outdoor dog access"]]),
        q("shade", "Shade", "How much shade did you find?", "Mostly shaded|Some shade|Little or none", ["Mostly shaded": ["shade", "shaded"], "Some shade": ["some shade"]]),
        q("price", "Cost", "How did the cost feel?", "Good value|About expected|A splurge", ["Good value": ["good value"]]),
        q("takeaway", "Takeaway", "Could you get food to take away?", "Available|Takeaway only|Not offered", ["Available": ["takeaway", "takeout"], "Takeaway only": ["takeaway", "takeout"]]),
        q("vegetarian", "Vegetarian choices", "How were the vegetarian meal choices?", "Several meals|One or two|None listed", ["Several meals": ["vegetarian choices", "vegetarian"], "One or two": ["some vegetarian choices"]]),
        q("vegan", "Vegan choices", "How were the vegan meal choices?", "Several meals|One or two|None listed", ["Several meals": ["vegan choices", "vegan"], "One or two": ["some vegan choices"]]),
        q("sharing", "Sharing", "Did the food work well for sharing?", "Easy to share|Mostly individual plates|Both worked", ["Easy to share": ["sharing plates"], "Both worked": ["sharing plates"]]),
        q("group_tables", "Group seating", "How did seating a group work?", "Large tables|Tables can combine|Mostly small tables", ["Large tables": ["group seating", "large tables"], "Tables can combine": ["group seating"]]),
        q("service", "Ordering", "How did you order?", "At the table|At a counter|Self-service", ["At the table": ["table service"], "At a counter": ["counter service"], "Self-service": ["self service"]]),
        q("portions", "Portions", "What kind of meal did a usual order make?", "Light bite|Full meal|Enough to share", ["Light bite": ["light bite"], "Full meal": ["full meal"], "Enough to share": ["shareable portions"]]),
        q("spice", "Spice", "Could you choose the heat level?", "Adjustable|Mild choices available|Mostly spicy", ["Adjustable": ["adjustable spice"], "Mild choices available": ["mild food options"]]),
        q("counter_seating", "Counter seating", "Could you eat at a counter?", "Good solo seating|A few counter seats|No counter seating", ["Good solo seating": ["solo counter seating"], "A few counter seats": ["counter seating"]]),
        q("alcohol_free", "Alcohol-free drinks", "What were the alcohol-free choices like?", "Interesting choices|The basics|None listed", ["Interesting choices": ["interesting alcohol free drinks"], "The basics": ["basic alcohol free drinks"]]),
        q("bread", "Bread to buy", "What bread could you buy?", "Whole loaves|Sliced bread|Both|No bread for sale", ["Whole loaves": ["bread loaves"], "Sliced bread": ["sliced bread"], "Both": ["bread loaves", "sliced bread"]]),
        q("rice", "Rice dishes", "What rice options stood out?", "Individual bowls|Dishes to share|A side with the meal", ["Individual bowls": ["rice bowls"], "Dishes to share": ["shared rice dishes"]]),
        q("small_plates", "Small plates", "Could you make a meal of small plates?", "Plenty to choose|A few starters|Mostly main courses", ["Plenty to choose": ["small plates"], "A few starters": ["starters"]]),
        q("set_menu", "Menu format", "What menu format was available?", "Order individual dishes|Set menu|Both", ["Set menu": ["set menu"], "Both": ["set menu", "a la carte"]]),
        q("dessert", "Dessert portions", "How were desserts served?", "Individual portions|Desserts to share|Both|No dessert offered", ["Individual portions": ["individual desserts"], "Desserts to share": ["sharing desserts"], "Both": ["individual desserts", "sharing desserts"]]),
        q("lunch", "Lunch", "How did it work for lunch?", "Quick lunch|Best with time to linger|Evening service only", ["Quick lunch": ["quick lunch"], "Best with time to linger": ["leisurely lunch"]]),
        q("dinner_pace", "Meal pace", "How did the meal unfold?", "Quick and casual|Relaxed meal|Long dining experience", ["Quick and casual": ["quick dinner", "casual dining"], "Relaxed meal": ["relaxed dining"]]),
        q("menu_guidance", "Menu help", "Was it easy to choose what to order?", "Clear descriptions|Staff helped|Hard to navigate", ["Clear descriptions": ["clear menu"], "Staff helped": ["helpful menu guidance"]]),
        q("dietary_menu", "Dietary information", "How clearly were ingredients or dietary options labeled?", "Clearly labeled|Staff explained|Little information", ["Clearly labeled": ["dietary information labels"], "Staff explained": ["staff explained dietary information"]]),
        q("fresh_herbs", "Herbs & extras", "Could you adjust herbs or toppings?", "Served on the side|Choices when ordering|Fixed preparation", ["Served on the side": ["herbs on the side"], "Choices when ordering": ["customizable toppings"]]),
        q("broth", "Broth choices", "What broth choices were there?", "Meat and plant-based|Meat-based only|Plant-based only", ["Meat and plant-based": ["plant based broth"], "Plant-based only": ["plant based broth"]]),
        q("noodles", "Noodles", "Could you choose your noodles?", "Several types|One house style|Custom preparation", ["Several types": ["noodle choices"], "One house style": ["house noodles"]]),
        q("dumplings", "Dumplings", "How could you try the dumplings?", "Mixed selection|Single filling per order|A larger sharing order", ["Mixed selection": ["dumpling sampler"], "A larger sharing order": ["sharing dumplings"]]),
        q("bao", "Bao", "Could you mix bao fillings?", "Mix individual buns|Mixed set|One filling per order", ["Mix individual buns": ["mix bao fillings"], "Mixed set": ["bao sampler"]]),
        q("dim_sum", "Dim sum service", "How was dim sum ordered?", "From a menu|From carts|Set selection", ["From carts": ["dim sum carts"], "From a menu": ["dim sum menu"]]),
        q("table_cooking", "Table cooking", "Was anything cooked at your table?", "Cook it yourself|Staff cook for you|Kitchen-prepared", ["Cook it yourself": ["table cooking"], "Staff cook for you": ["tableside cooking"]]),
        q("ventilation", "Smoke", "How smoky did the space feel?", "Little or no smoke|Some smoke|Quite smoky", ["Little or no smoke": ["little smoke on visit"]]),
        q("hotpot", "Hot-pot broth", "Could you choose more than one broth?", "Split pot available|One broth per pot|Individual pots", ["Split pot available": ["split hot pot"], "Individual pots": ["individual hot pot"]]),
        q("roast_meats", "Roast dishes", "How were roast dishes offered?", "Individual plates|Shared portions|Not on this menu", ["Individual plates": ["roast meat plates"], "Shared portions": ["shared roast dishes"]]),
        q("skewers", "Skewers", "How were skewers ordered?", "By the skewer|Mixed set|Set meal", ["By the skewer": ["individual skewers"], "Mixed set": ["skewer sampler"]]),
        q("sushi_menu", "Sushi ordering", "How could you order sushi?", "Individual pieces or rolls|Chef's selection|Both", ["Individual pieces or rolls": ["sushi a la carte"], "Chef's selection": ["chef selection sushi"], "Both": ["chef selection sushi", "sushi a la carte"]]),
        q("curry", "Curry portions", "How did curry orders come?", "Complete individual meal|Dishes and sides separately|Shared set meal", ["Complete individual meal": ["curry meal"], "Shared set meal": ["curry set meal"]]),
        q("crispy_takeaway", "Takeaway texture", "How did fried food hold up to takeaway?", "Stayed crisp|Best eaten right away|Did not try takeaway", ["Stayed crisp": ["crispy takeaway"]]),
        q("flatbread", "Flatbreads", "Were flatbreads made to order?", "Made to order|Ready to pick up|Not offered", ["Made to order": ["fresh flatbread"]]),
        q("dips", "Dips & sides", "Could you try several dips or sides?", "Mixed plate|Order separately|Limited choices|Not offered", ["Mixed plate": ["mixed dips or sides"], "Order separately": ["dips or sides"]]),
        q("coffee_after", "After-meal coffee", "Could you linger for coffee or tea?", "A nice place to linger|Drinks but little seating|Not offered", ["A nice place to linger": ["after dinner coffee"]]),
        q("stew", "Stews & slow cooking", "How were slow-cooked dishes served?", "Individual meal|Good to share|Not on this menu", ["Good to share": ["shared stews"]]),
        q("shared_platter", "Shared platters", "Could you order a platter for the table?", "Easy mixed platter|Choose dishes separately|Mostly individual meals", ["Easy mixed platter": ["shared platter"]]),
        q("grilled", "Grilled dishes", "What was the grilled-food selection like?", "Several choices|One house specialty|Not on this menu", ["Several choices": ["grilled food choices"], "One house specialty": ["grill specialty"]]),
        q("pastry", "Pastry availability", "What pastry choice was left when you arrived?", "Good selection|Limited selection|Sold out", ["Good selection": ["pastry selection on visit"], "Limited selection": ["limited pastries on visit"]]),
        q("seafood", "Seafood choices", "How was seafood presented?", "Daily choices|Regular menu|Ask what is available", ["Daily choices": ["daily seafood"]]),
        q("pasta", "Pasta portions", "How did a pasta order work as a meal?", "A full meal|Best with another course|Easy to share", ["A full meal": ["pasta meal"], "Easy to share": ["sharing pasta"]]),
        q("pizza", "Pizza ordering", "How was pizza sold?", "By the slice|Whole pies|Both", ["By the slice": ["pizza slices"], "Whole pies": ["whole pizza"], "Both": ["pizza slices", "whole pizza"]]),
        q("tapas", "Tapas pace", "Could you order small plates as you went?", "Easy to add rounds|Order together|Set menu only", ["Easy to add rounds": ["tapas rounds"]]),
        q("wine_by_glass", "Wine", "How was the by-the-glass selection?", "Plenty of choices|A short list|Bottles only|No wine listed", ["Plenty of choices": ["wine by the glass"], "A short list": ["wine by the glass"]]),
        q("fondue", "Fondue", "How were fondue portions arranged?", "For two|For a group|Individual servings", ["For two": ["fondue for two"], "For a group": ["group fondue"]]),
        q("breakfast", "Breakfast timing", "When was breakfast served?", "All day|Morning only|Weekend service", ["All day": ["all day breakfast"]]),
        q("tacos", "Taco ordering", "Could you mix taco fillings?", "Order individually|Mixed plate|One filling per order", ["Order individually": ["individual tacos"], "Mixed plate": ["mixed taco plate"]]),
        q("salsa", "Salsa", "How did you choose salsa?", "Self-serve selection|Choose when ordering|House salsa only|No salsa offered", ["Self-serve selection": ["salsa bar"]]),
        q("sandwich", "Sandwiches", "Could you adjust your sandwich?", "Build your own|Some swaps|Fixed menu", ["Build your own": ["custom sandwiches"], "Some swaps": ["sandwich substitutions"]]),
        q("burger", "Burger alternatives", "Were non-meat burgers offered?", "Several options|One option|None listed", ["Several options": ["vegetarian burgers"], "One option": ["vegetarian burger"]]),
        q("barbecue", "Barbecue availability", "How was the barbecue availability?", "Full selection|Some items sold out|Preorder recommended", ["Full selection": ["barbecue selection"]]),
        q("wings", "Wing flavors", "Could you mix sauces in an order?", "Easy to mix|Large orders only|One sauce per order", ["Easy to mix": ["mixed wing flavors"]]),
        q("steak", "Steak sides", "How were sides ordered?", "Included with the steak|Order separately|Sharing sides", ["Included with the steak": ["steak sides included"], "Sharing sides": ["sharing sides"]]),
        q("bowl", "Bowls", "Could you build your own bowl?", "Build your own|Choose a set bowl|Both", ["Build your own": ["custom bowls"], "Both": ["custom bowls"]]),
        q("soup", "Soup meal", "What could you pair with soup?", "Bread or sandwich combo|Sides separately|Soup on its own", ["Bread or sandwich combo": ["soup combo"]]),
        q("oysters", "Oysters", "How were oysters ordered?", "Individually|By the half-dozen or dozen|Mixed tasting", ["Individually": ["individual oysters"], "Mixed tasting": ["oyster tasting"]]),
        q("gluten_menu", "Gluten labeling", "How were gluten-free choices identified?", "Clearly marked|Staff explained|Not clear", ["Clearly marked": ["gluten free menu labels"]]),
        q("halal_menu", "Halal information", "How was halal information provided?", "Clearly posted|Staff confirmed|Not clear", ["Clearly posted": ["posted halal information"], "Staff confirmed": ["staff confirmed halal information"]]),
        q("laptop", "Laptop use", "What was the laptop setup?", "Laptops welcome|Limited times or areas|Not allowed", ["Laptops welcome": ["laptops welcome", "laptop use allowed"], "Limited times or areas": ["limited laptop use"]]),
        q("beans", "Coffee to take home", "Could you buy beans to take home?", "Several roasts|One house roast|No beans for sale", ["Several roasts": ["coffee beans"], "One house roast": ["coffee beans"]]),
        q("tea", "Tea service", "How was tea served?", "Individual cups|Sharing pots|Both", ["Individual cups": ["tea by the cup"], "Sharing pots": ["shared tea pots"], "Both": ["tea by the cup", "shared tea pots"]]),
        q("tea_shop", "Tea to take home", "How could you buy tea?", "Loose leaf by weight|Packaged tea|Both", ["Loose leaf by weight": ["loose leaf tea by weight"], "Packaged tea": ["packaged tea"], "Both": ["loose leaf tea by weight", "packaged tea"]]),
        q("milk", "Milk options", "What milk alternatives were offered?", "Several choices|One alternative|None listed", ["Several choices": ["milk alternatives"], "One alternative": ["milk alternative"]]),
        q("juice", "Juice preparation", "How was juice prepared?", "Made to order|Ready-made bottles|Both", ["Made to order": ["fresh juice"]]),
        q("smoothie", "Smoothie changes", "Could you adjust smoothie ingredients?", "Easy to customize|Some changes|Fixed recipes", ["Easy to customize": ["custom smoothies"]]),
        q("toppings", "Toppings", "Could you choose toppings?", "Build your own|Some choices|Set combinations", ["Build your own": ["custom toppings"]]),
        q("cake", "Cake orders", "How did cake ordering work?", "Slices ready to buy|Whole cakes ready|Custom preorder", ["Slices ready to buy": ["cake slices"], "Whole cakes ready": ["whole cakes"], "Custom preorder": ["custom cakes"]]),
        q("frozen_treat", "Frozen treats", "Were dairy-free choices available?", "Several flavors|One flavor|None listed", ["Several flavors": ["dairy free ice cream"], "One flavor": ["dairy free flavor"]]),
        q("gift_packaging", "Gifts", "Could you get items packaged as a gift?", "Gift boxes|Simple wrapping|Not offered", ["Gift boxes": ["gift boxes"], "Simple wrapping": ["gift wrapping"]]),
        q("tasting", "Samples & tastings", "Could you sample or taste before choosing?", "Samples|Tasting session|Both|Neither offered", ["Samples": ["samples offered"], "Tasting session": ["tasting session offered"], "Both": ["samples offered", "tasting session offered"]]),
        q("resident_animals", "Animal visits", "Was there a charge to spend time with the animals?", "Included with a purchase|Separate entry fee|Free entry", ["Included with a purchase": ["animal cafe entry with purchase"], "Separate entry fee": ["paid animal cafe entry"], "Free entry": ["free animal cafe entry"]]),
        q("beer_selection", "Beer selection", "What was the beer selection like?", "Rotating taps|House beers|Mostly bottles or cans", ["Rotating taps": ["rotating beer taps"], "House beers": ["house beer selection"]]),
        q("cocktails", "Cocktails", "How did the cocktail menu work?", "House creations|Classic cocktails|Both", ["House creations": ["signature cocktails"], "Classic cocktails": ["classic cocktails"], "Both": ["signature cocktails", "classic cocktails"]]),
        q("screens", "Watching sports", "Could you comfortably watch a game?", "Good view of screens|A few viewing spots|No screens", ["Good view of screens": ["sports screens", "watch sports"]]),
        q("games", "Games", "How did getting a game work?", "Drop in and play|Wait for a turn|Book a slot", ["Drop in and play": ["drop in games"], "Book a slot": ["bookable games"]]),
        q("live_music", "Live music", "Was there live music during your visit?", "Live performers|Recorded music|No music", ["Live performers": ["live music"]]),
        q("dancing", "Dancing", "Was there room to dance?", "Dedicated dance floor|Some space|Mostly seated", ["Dedicated dance floor": ["dance floor"], "Some space": ["dancing space"]]),
        q("door", "Entry", "How did entry work for your visit?", "No cover|Cover at the door|Ticket needed", ["No cover": ["free entry on visit"], "Ticket needed": ["ticketed entry"]]),
        q("coat_storage", "Coat storage", "Was there somewhere to leave a coat?", "Coat check|Hooks or racks|Not available", ["Coat check": ["coat check"]]),
        q("karaoke", "Karaoke", "What was the karaoke setup?", "Private rooms|Open stage|Both", ["Private rooms": ["private karaoke rooms"], "Open stage": ["open stage karaoke"], "Both": ["private karaoke rooms", "open stage karaoke"]]),
        q("karaoke_charge", "Karaoke payment", "How was karaoke charged?", "By room or hour|Per person|Per song|Included", ["By room or hour": ["time based karaoke"], "Per song": ["karaoke per song"], "Included": ["karaoke included"]]),
        q("show_seating", "Show seating", "How was show seating arranged?", "Reserved seats|First come, first served|Standing", ["Reserved seats": ["reserved seating"], "Standing": ["standing show"]]),
        q("food_at_bar", "Food", "Was food available with drinks?", "Full menu|Snacks|No food", ["Full menu": ["food available", "full food menu"], "Snacks": ["snacks"]]),
        q("smoking_area", "Smoking areas", "How were smoking and smoke-free areas arranged?", "Clearly separated|Some separation|No separation|No smoking area found", ["Clearly separated": ["separate smoke free area"]]),
        q("cider", "Cider tasting", "Could you compare ciders?", "Tasting flight|Individual pours|Bottles only", ["Tasting flight": ["cider flight"]]),
        q("sake", "Sake tasting", "Could you try smaller sake pours?", "Tasting flight|By the glass|Bottles only", ["Tasting flight": ["sake flight"], "By the glass": ["sake by the glass"]]),
        q("vineyard", "Vineyard access", "Could you explore outside the tasting room?", "Self-guided grounds|Guided tour only|Tasting room only", ["Self-guided grounds": ["vineyard grounds"], "Guided tour only": ["vineyard tour"]]),
        q("distillery", "Distillery visits", "Could you see how it is made?", "Tour available|Tasting only|Shop only", ["Tour available": ["distillery tour"]]),
        q("water_refill", "Water refill", "Could you refill drinking water?", "Free refill|Purchase required|None found", ["Free refill": ["water refill"]]),
        q("path_surface", "Path surface", "What surface did you use most?", "Paved|Firm gravel|Uneven trail|Sand|Grass", ["Paved": ["paved path"], "Firm gravel": ["gravel path"], "Uneven trail": ["uneven trail"], "Sand": ["sand path"], "Grass": ["grass path"]]),
        q("incline", "Incline", "How steep was the route you took?", "Mostly level|Some climbs|Steep sections|Many steps", ["Mostly level": ["flat route", "level path"]]),
        q("trail_marking", "Trail signs", "How easy was the route to follow?", "Clearly marked|Some unclear turns|Navigation needed", ["Clearly marked": ["marked trail"]]),
        q("trail_length", "Time on the trail", "How much walking time would you allow?", "Under an hour|One to three hours|Half a day or more", ["Under an hour": ["short hike"]]),
        q("picnic", "Picnic spots", "What picnic setup did you find?", "Tables available|Ground space|No good spot", ["Tables available": ["picnic tables"], "Ground space": ["picnic space"]]),
        q("leash", "Leash rules", "What pet-dog rule was posted for this area?", "Leash required|Signed off-leash area|No pet dogs|No sign found", ["Signed off-leash area": ["off leash dog area"], "Leash required": ["dogs on leash"]]),
        q("beach_rinse", "Rinse facilities", "Could you rinse sand off?", "Outdoor showers|Foot rinse|None found", ["Outdoor showers": ["beach showers", "rinse showers"], "Foot rinse": ["foot rinse"]]),
        q("beach_access", "Beach access", "What was the route down to the beach like?", "Mostly level|Steps|Steep or uneven ground", ["Mostly level": ["mostly level beach route"], "Steps": ["beach access steps"]]),
        q("lifeguard", "Lifeguards", "Were lifeguards on duty during your visit?", "On duty|Station but no guard|No station seen", ["On duty": ["lifeguards observed"]]),
        q("water_edge", "Water access", "How could you reach the water?", "Gentle shoreline|Dock or platform|Steep or limited access", ["Gentle shoreline": ["gentle water access"], "Dock or platform": ["water access dock"]]),
        q("boat_access", "Boat access", "Was there a launch or dock?", "Boat ramp|Dock|Both|Neither found", ["Boat ramp": ["boat ramp"], "Dock": ["dock"], "Both": ["boat ramp", "dock"]]),
        q("ferry_access", "Island arrival", "How did you get onto the island?", "Bridge or causeway|Public ferry|Private boat|By air|Another way", ["Bridge or causeway": ["island bridge"], "Public ferry": ["island ferry"]]),
        q("view_access", "Viewpoint access", "How much walking to reach the view?", "Beside arrival|Under 15 minutes|Longer walk", ["Beside arrival": ["view near arrival"], "Under 15 minutes": ["short walk viewpoint"]]),
        q("shelter", "Weather shelter", "Was there shelter on the route or grounds?", "Plenty|A few spots|None found", ["Plenty": ["weather shelter"], "A few spots": ["some shelter"]]),
        q("waterfall_view", "Waterfall view", "How close could you get to the falls?", "View from a platform|Trail to the base|Distant viewpoint", ["Trail to the base": ["waterfall base trail"], "View from a platform": ["waterfall viewing platform"]]),
        q("hot_spring", "Soaking setup", "How was the hot-spring access arranged?", "Managed pools|Natural pools|Viewing only", ["Managed pools": ["hot spring pools"], "Natural pools": ["natural hot spring"]]),
        q("cave", "Cave visit", "What was the visit format?", "Guided tour|Self-guided visitor route|No managed visitor route", ["Guided tour": ["cave tour"], "Self-guided visitor route": ["self guided cave route"]]),
        q("wildlife_viewing", "Wildlife viewing", "What viewing setup was available?", "Hides or platforms|Open trails|Guided viewing", ["Hides or platforms": ["wildlife viewing hide"], "Guided viewing": ["guided wildlife viewing"]]),
        q("garden_labels", "Plant labels", "Were plants identified along the way?", "Clearly labeled|Some labels|Few or no labels", ["Clearly labeled": ["labeled plants"]]),
        q("playground_age", "Play equipment", "Who did the play equipment seem designed for?", "Toddlers|Older children|Separate areas for both", ["Toddlers": ["toddler playground"], "Older children": ["older child playground"], "Separate areas for both": ["toddler playground", "older child playground"]]),
        q("fenced", "Enclosure", "Was the play area fenced?", "Fully fenced|Partly fenced|Open area", ["Fully fenced": ["fenced play area"]]),
        q("camp_booking", "Campsites", "How did you secure your campsite?", "Reserved a site|Chose a first-come site|Used a general permit", ["Reserved a site": ["reserved campsite visit"], "Chose a first-come site": ["first come campsite used"], "Used a general permit": ["camping permit used"]]),
        q("camp_toilet", "Camp toilets", "What toilet facilities were there?", "Flush toilets|Non-flush toilets|None found", ["Flush toilets": ["camp flush toilets"], "Non-flush toilets": ["non flush camp toilets"]]),
        q("camp_power", "Hookups", "What hookups were offered?", "Water and power|Power only|Water only|No hookups", ["Water and power": ["water hookup", "electric hookup"], "Power only": ["electric hookup"], "Water only": ["water hookup"]]),
        q("camp_surface", "Pitch level", "How level was your pitch?", "Mostly level|Some sloping ground|Very uneven", ["Mostly level": ["level campsite pitch"]]),
        q("kitchen", "Cooking", "What cooking setup was available?", "Full kitchen|Basic cooking area|No cooking setup", ["Full kitchen": ["full kitchen"], "Basic cooking area": ["basic kitchen"]]),
        q("fishing_setup", "Fishing access", "How could you fish here?", "From shore|From a pier|Boat needed", ["From shore": ["shore fishing"], "From a pier": ["pier fishing"]]),
        q("fishing_gear", "Fishing gear", "Was fishing gear available?", "Included|Rent separately|Bring your own", ["Included": ["fishing gear included"], "Rent separately": ["fishing gear rental"]]),
        q("fishing_pier_setup", "Pier facilities", "What was provided for fishing on the pier?", "Rod holders|Cleaning station|Both|Neither found", ["Rod holders": ["pier rod holders"], "Cleaning station": ["fish cleaning station"], "Both": ["pier rod holders", "fish cleaning station"]]),
        q("ski_rental", "Ski equipment", "Where was rental equipment available?", "On site|Nearby only|No rental found", ["On site": ["onsite ski rental"], "Nearby only": ["nearby ski rental"]]),
        q("ski_levels", "Ski terrain", "What terrain did you find?", "Beginner areas|Mixed levels|Mostly advanced", ["Beginner areas": ["beginner skiing"], "Mixed levels": ["mixed ski levels"]]),
        q("bike_trails", "Cycling routes", "What type of riding was it set up for?", "Easy paths|Mixed trails|Technical riding", ["Easy paths": ["easy cycling paths"], "Technical riding": ["technical cycling trails"]]),
        q("skate_features", "Skate features", "What was the skate setup?", "Street features|Bowls or ramps|Both", ["Street features": ["street skate park"], "Bowls or ramps": ["skate bowl", "skate ramps"], "Both": ["street skate park", "skate bowl"]]),
        q("offroad", "Vehicle access", "What did the signed route require?", "Standard vehicle|High clearance|Four-wheel drive|No requirement found", ["High clearance": ["high clearance route"], "Four-wheel drive": ["four wheel drive route"]]),
        q("adventure_guidance", "Guidance", "How was the activity supervised?", "Guide included|Guide optional|Self-guided", ["Guide included": ["guided adventure"]]),
        q("admission", "Admission cost", "Was there an admission charge?", "Free entry|Paid entry|Suggested donation", ["Free entry": ["free entry", "free admission"], "Paid entry": ["paid admission"], "Suggested donation": ["suggested admission donation"]]),
        q("visit_time", "Visit length", "How much time would you set aside?", "A short stop|About an hour|A few hours|Most of a day", ["A short stop": ["quick stop"], "About an hour": ["one hour visit"]]),
        q("interpretation", "Context", "Was the place's story explained?", "Good signs or displays|A guide helps|Little information", ["Good signs or displays": ["interpretive signs"]]),
        q("guided_tour", "Tours", "Could you join a guided tour?", "Regular walk-up tours|Book ahead|Self-guided only", ["Regular walk-up tours": ["walk up tour"], "Book ahead": ["bookable guided tour"]]),
        q("photography", "Photography", "What photography rule was posted?", "Photos allowed|Restricted areas|No photos|No rule found", ["Photos allowed": ["photography allowed"]]),
        q("exhibits", "Exhibitions", "What kind of exhibitions were on?", "Permanent collection|Temporary exhibition|Both", ["Temporary exhibition": ["temporary exhibition"], "Both": ["temporary exhibition", "permanent collection"]]),
        q("hands_on", "Hands-on activities", "Were there activities to try yourself?", "Lots to try|A few activities|Viewing only", ["Lots to try": ["hands on activities"], "A few activities": ["hands on activities"]]),
        q("art_classes", "Making art", "Could visitors make something?", "Drop-in activity|Book a workshop|Viewing only", ["Drop-in activity": ["drop in art"], "Book a workshop": ["art workshop"]]),
        q("sightlines", "Sightlines", "How was the view from your spot?", "Clear view|Some obstruction|Hard to see", ["Clear view": ["clear sightlines"]]),
        q("acoustics", "Sound", "How was the sound from your spot?", "Clear and balanced|Uneven sound|Hard to hear", ["Clear and balanced": ["good acoustics"]]),
        q("screen_comfort", "Cinema seats", "What were the cinema seats like?", "Reclining|Comfortable standard seats|Tight seating", ["Reclining": ["reclining cinema seats"]]),
        q("cinema_snacks", "Cinema food", "What food was available for the film?", "Snacks and drinks|Meals available|No food sold", ["Snacks and drinks": ["cinema snacks"], "Meals available": ["cinema meals"]]),
        q("view_indoor", "Viewing area", "Was the main viewing area indoors or out?", "Indoors|Outdoors|Both", ["Indoors": ["indoor viewing"], "Outdoors": ["outdoor viewing"], "Both": ["indoor and outdoor viewing"]]),
        q("animal_paths", "Walking route", "How much walking between exhibits?", "Compact route|Spread-out grounds|Transport available", ["Compact route": ["compact visitor route"], "Transport available": ["visitor transport"]]),
        q("ride_queues", "Ride queues", "How did ride queues work?", "Short waits|Long waits|Timed or virtual queue", ["Short waits": ["short ride waits"], "Timed or virtual queue": ["virtual queue"]]),
        q("ride_storage", "Belongings", "Where could you put belongings for the activity?", "Lockers|Storage by the activity|No storage", ["Lockers": ["lockers"], "Storage by the activity": ["activity storage"]]),
        q("ride_cabin", "Ride enclosure", "What was your seat or cabin like?", "Fully enclosed|Open air|Partly covered", ["Fully enclosed": ["enclosed ride cabin"], "Open air": ["open air ride seat"], "Partly covered": ["covered ride seat"]]),
        q("ride_restrictions", "Participation rules", "Were height or age requirements easy to find?", "Clearly posted|Ask staff|Not clear", ["Clearly posted": ["posted activity requirements"]]),
        q("game_payment", "Game payment", "How did you pay to play?", "Per game|Time-based|Included with entry|Free play", ["Included with entry": ["games included with entry"], "Free play": ["free games on visit"]]),
        q("equipment", "Equipment", "How was equipment provided?", "Included|Rent separately|Bring your own", ["Included": ["equipment included"], "Rent separately": ["equipment rental"]]),
        q("instruction", "Instruction", "What introduction was offered to first-timers?", "Included introduction|Book a lesson|No introduction offered", ["Included introduction": ["introductory instruction"], "Book a lesson": ["lessons available"]]),
        q("board_games", "Game library", "What was the board-game selection like?", "Easy group games|Strategy-heavy|A broad mix", ["Easy group games": ["party board games"], "Strategy-heavy": ["strategy board games"]]),
        q("indoor_play", "Indoor play", "How were play ages separated?", "Separate age areas|One shared area|One age group", ["Separate age areas": ["separate child play areas"]]),
        q("event_food", "Event food", "What food arrangements were possible?", "Food sold on site|Arrange catering|Bring your own", ["Bring your own": ["bring your own food"], "Arrange catering": ["event catering"]]),
        q("event_layout", "Event space", "How flexible was the space?", "Movable seating|Fixed layout|Separate rooms", ["Movable seating": ["flexible event seating"], "Separate rooms": ["separate event rooms"]]),
        q("barbecue_setup", "Barbecue setup", "What cooking facilities were there?", "Shared grills|Bookable grills|Bring your own", ["Shared grills": ["public grills"], "Bookable grills": ["bookable barbecue grills"]]),
        q("fitness_dropin", "Drop-in training", "Could a visitor train here?", "Day pass|Trial session|Members only", ["Day pass": ["gym day pass"], "Trial session": ["fitness trial"]]),
        q("gym_equipment", "Gym equipment", "What was the equipment focus?", "Free weights|Machines and cardio|A broad mix|Bodyweight setup", ["Free weights": ["free weights"], "Machines and cardio": ["cardio machines"], "A broad mix": ["free weights", "cardio machines"], "Bodyweight setup": ["bodyweight training setup"]]),
        q("changing", "Changing facilities", "What changing facilities were there?", "Changing rooms and showers|Changing area only|None found", ["Changing rooms and showers": ["changing rooms", "showers"], "Changing area only": ["changing area"]]),
        q("class_size", "Session size", "How many people trained together?", "On my own|One-to-one|Small group|Larger group", ["On my own": ["solo training session"], "One-to-one": ["one to one training session"], "Small group": ["small training group"]]),
        q("yoga_style", "Yoga pace", "How did the class move?", "Slow and restorative|Steady flow|Fast and vigorous", ["Slow and restorative": ["restorative yoga"], "Steady flow": ["flow yoga"]]),
        q("pilates_format", "Pilates format", "What Pilates equipment did the session use?", "Reformer|Mat|Mixed apparatus", ["Reformer": ["reformer pilates"], "Mat": ["mat pilates"], "Mixed apparatus": ["pilates apparatus"]]),
        q("pilates_intro", "Pilates introduction", "How were first-timers introduced to the session?", "Separate introduction|Help during class|No introduction offered", ["Separate introduction": ["pilates introduction"], "Help during class": ["pilates introductory help"]]),
        q("crossfit_scaling", "Workout scaling", "Were scaled versions of the workout explained?", "Clearly coached|Explained when asked|Not explained", ["Clearly coached": ["scaled crossfit workouts explained"], "Explained when asked": ["crossfit scaling explained when asked"]]),
        q("crossfit_format", "CrossFit session", "How was training structured?", "Coached workout of the day|Open gym|Both", ["Coached workout of the day": ["coached crossfit wod"], "Open gym": ["crossfit open gym"], "Both": ["coached crossfit wod", "crossfit open gym"]]),
        q("functional_format", "Functional training", "How was the session organized?", "Coached circuits|Individual program|Open training", ["Coached circuits": ["functional fitness circuits"], "Individual program": ["individual training program"]]),
        q("coaching", "Coaching", "How was technique feedback offered?", "Regular individual feedback|Help when asked|Mostly self-directed", ["Regular individual feedback": ["technique coaching"]]),
        q("court_booking", "Court access", "How did you get time on a court?", "Open play|Book a court|Club or league only", ["Open play": ["open court play"], "Book a court": ["court reservations"]]),
        q("court_lights", "Court lighting", "Were court lights available?", "Lit during evening play|Lights but not on|No lights seen", ["Lit during evening play": ["lit courts"]]),
        q("activity_lights", "Lighting", "Was the activity area lit for evening use?", "Lit during my visit|Lights but not on|No lights seen", ["Lit during my visit": ["activity area lit on visit"]]),
        q("volleyball_surface", "Volleyball surface", "What surface did you play on?", "Sand|Indoor court|Outdoor hard court|Grass", ["Sand": ["sand volleyball", "beach volleyball"], "Indoor court": ["indoor volleyball"], "Outdoor hard court": ["outdoor volleyball"], "Grass": ["grass volleyball"]]),
        q("volleyball_net", "Volleyball net", "Was a net ready to use?", "Net set up|Provided on request|No net set up", ["Net set up": ["volleyball net provided"], "Provided on request": ["volleyball net on request"]]),
        q("tennis_surface", "Tennis surface", "What was the court surface?", "Hard court|Clay|Grass|Artificial turf", ["Hard court": ["hard tennis court"], "Clay": ["clay tennis court"], "Grass": ["grass tennis court"]]),
        q("pickleball_lines", "Pickleball court", "How was the pickleball court set up?", "Dedicated courts|Shared court markings|Temporary setup", ["Dedicated courts": ["dedicated pickleball courts"]]),
        q("basketball", "Basketball setup", "What court setup was available?", "Full court|Half court|Single hoop", ["Full court": ["full basketball court"], "Half court": ["half basketball court"]]),
        q("field_surface", "Field surface", "What was the playing surface?", "Natural grass|Artificial turf|Hard surface", ["Natural grass": ["grass playing field"], "Artificial turf": ["turf playing field"]]),
        q("field_goals", "Goals", "Were goals already set up?", "Full-size goals|Small goals|Bring equipment", ["Full-size goals": ["full size soccer goals"], "Small goals": ["small soccer goals"]]),
        q("pool_use", "Pool use", "How was swimming organized?", "Lap lanes|Open swim|Separate times for both", ["Lap lanes": ["lap swimming"], "Open swim": ["open swimming"], "Separate times for both": ["lap swimming", "open swimming"]]),
        q("pool_setting", "Pool setting", "Was the pool indoors or outdoors?", "Indoors|Outdoors|Both", ["Indoors": ["indoor pool"], "Outdoors": ["outdoor pool"], "Both": ["indoor pool", "outdoor pool"]]),
        q("golf", "Golf format", "What kind of golf could you play?", "Full course|Short course|Practice facilities", ["Full course": ["golf course"], "Short course": ["short golf course"], "Practice facilities": ["golf practice"]]),
        q("golf_hire", "Golf hire", "Could you hire clubs?", "Rental sets|Limited clubs|Bring your own", ["Rental sets": ["golf club rental"]]),
        q("golf_simulator", "Indoor golf", "What was the indoor-golf setup?", "Private simulator bay|Shared bays|Putting or practice only", ["Private simulator bay": ["private golf simulator"], "Shared bays": ["golf simulator"]]),
        q("ice_sessions", "Ice sessions", "How did public skating work?", "Drop-in session|Booked session|Club sessions only", ["Drop-in session": ["public ice skating"]]),
        q("sauna", "Sauna setup", "What heat facilities were available?", "Dry sauna|Steam room|Both|None found", ["Dry sauna": ["dry sauna"], "Steam room": ["steam room"], "Both": ["dry sauna", "steam room"]]),
        q("treatment_booking", "Appointments", "How did you arrange this visit?", "Walked in|Booked an appointment|Referral then appointment", ["Walked in": ["walk in appointment visit"], "Booked an appointment": ["booked appointment visit"]]),
        q("privacy", "Privacy", "How private was the appointment space?", "Private room|Separated area|Shared space", ["Private room": ["private appointment room"]]),
        q("treatment_info", "Before you arrive", "Were preparation instructions clear?", "Clear instructions|Ask in advance|Little information", ["Clear instructions": ["clear appointment instructions"]]),
        q("massage", "Massage options", "Could you choose the massage style or pressure?", "Both discussed|Some choices|Fixed treatment", ["Both discussed": ["custom massage pressure"]]),
        q("eye_shop", "Eyewear", "Could you try eyewear at the same place?", "Full selection|Small selection|Appointments only", ["Full selection": ["eyewear selection"]]),
        q("pharmacy", "Pharmacy service", "How did collecting a prescription work?", "Ready on arrival|Prepared while waiting|Return later", ["Ready on arrival": ["prescription ready on arrival"]]),
        q("lab_booking", "Lab appointments", "How were tests scheduled?", "Walk-in queue|Booked time|Referral and booking", ["Walk-in queue": ["walk in lab"]]),
        q("rehab_space", "Exercise space", "Was there space for guided exercises?", "Equipped exercise area|Small treatment space|Treatment only", ["Equipped exercise area": ["rehab exercise area"]]),
        q("vet_wait", "Animal waiting areas", "How were animals separated while waiting?", "Separate areas|Some separation|Shared waiting room", ["Separate areas": ["separate pet waiting areas"]]),
        q("retreat", "Retreat schedule", "How structured was the day?", "Scheduled activities|Optional sessions|Mostly your own time", ["Optional sessions": ["optional retreat activities"]]),
        q("changing_privacy", "Changing privacy", "How was changing arranged?", "Private cubicles|Shared changing room|No changing area", ["Private cubicles": ["private changing cubicles"]]),
        q("arrival_parking", "Arrival parking", "How was parking on arrival?", "On-site spaces|Nearby street parking|Difficult to find", ["On-site spaces": ["on site parking"]]),
        q("visitor_info", "Visitor information", "Could you get practical visitor information?", "Staff available|Useful signs or map|Little information", ["Staff available": ["staffed visitor information"]]),
        q("group_instruction", "Learning together", "How were lessons arranged?", "Group lessons|Private lessons|Both", ["Group lessons": ["group lessons"], "Private lessons": ["private lessons"], "Both": ["group lessons", "private lessons"]])
    ]

    private static func q(
        _ id: String, _ label: String, _ prompt: String, _ choices: String,
        _ search: [String: [String]] = [:]
    ) -> PlaceCheckInQuestion {
        PlaceCheckInQuestion(
            id: keyPrefix + id,
            displayLabel: label,
            prompt: prompt,
            options: choices.components(separatedBy: "|"),
            searchableAnswers: search
        )
    }
}
