import Foundation

extension PlaceCheckInQuestionCatalog {
    /// Each row is a deliberate subtype selection. Shared cuisine rows reflect
    /// equivalent practical dining needs, not assumed dishes or national traits.
    /// Specialized formats below get their own questions when the format itself
    /// gives us reliable context. A nationality never implies spice or a diet.
    static let coreProfiles: [PlaceCheckInQuestionProfile] = [
        p("restaurants_food", "Restaurant|Thai|Vietnamese|Chinese|Korean|Japanese|Indian|Asian fusion|Sushi|Ramen|Dumplings|Bao buns|Noodles|Dim sum|Cantonese|Taiwanese|Izakaya|Yakitori|North Indian|South Indian|Pakistani|Sri Lankan|Bangladeshi|Nepalese|Malaysian|Singaporean|Indonesian|Filipino|Burmese|Cambodian|Laotian|Asian|Tibetan|Mongolian|Georgian|Armenian|Uzbek|Mongolian BBQ|Japanese curry|Tonkatsu|Afghan|Middle Eastern|Lebanese|Persian|Turkish|Israeli|Palestinian|Syrian|Iraqi|Jordanian|Yemeni|Egyptian|Moroccan|Tunisian|Algerian|Ethiopian|Eritrean|Somali|Kenyan|Nigerian|Ghanaian|Senegalese|South African|African|Falafel|Gyro|Kebab|Shawarma|Halal|Italian|Mediterranean|Greek|French|Spanish|Tapas|Portuguese|Basque|German|Austrian|Bavarian|Swiss|Dutch|Belgian|British|Irish|Scandinavian|Swedish|Norwegian|Finnish|Danish|Polish|Ukrainian|Russian|Czech|Slovak|Hungarian|Romanian|Croatian|Serbian|Bosnian|Bulgarian|Albanian|Slovenian|Lithuanian|European|Eastern European|Pizza|Fish & chips|Fondue|American|Canadian|Mexican|Tex-Mex|Caribbean|Jamaican|Puerto Rican|Dominican|Haitian|Panamanian|Cuban|Brazilian|Argentinian|Colombian|Chilean|Peruvian|Venezuelan|Ecuadorian|Bolivian|Uruguayan|Salvadoran|Guatemalan|South American|Latin American|Southwestern|Cajun|Californian|Hawaiian|Poke|Australian|New Zealand|Fijian|Samoan|Tongan|Burgers|Diner|Hot dogs|Barbecue|Wings|Steakhouse|Bar & grill|Burrito|Taco|Sandwich|Bagel|Deli|Salad|Bistro|Breakfast|Brunch|Soup|Chicken|Seafood|Oyster bar|Gastropub", "arrival_parking outdoor_seating dietary_options"),
        p("restaurants_food", "Hot pot|Yakiniku|Korean BBQ|Japanese BBQ", "ventilation booking_policy dietary_options"),
        p("restaurants_food", "Taco stand|Taco truck|Snack bar", "arrival_parking waiting dietary_options"),
        p("restaurants_food", "Food court", "seating restroom dietary_options"),
        p("restaurants_food", "Vegetarian", "arrival_parking outdoor_seating vegan"),
        p("restaurants_food", "Vegan", "arrival_parking outdoor_seating gluten_free_options"),
        p("restaurants_food", "Gluten-free", "arrival_parking outdoor_seating dietary_menu"),
        p("restaurants_food", "Food truck|Food stand|Fast food|Takeout", "arrival_parking waiting dietary_options"),
        p("restaurants_food", "Fine dining", "arrival_parking booking_policy dietary_options"),
        p("restaurants_food", "Buffet|Cafeteria|Casual/family", "arrival_parking outdoor_seating dietary_options"),

        p("coffee_tea_sweets", "Coffee shop", "laptop outlets dog_access"),
        p("coffee_tea_sweets", "Cafe", "laptop outlets dog_access"),
        p("coffee_tea_sweets", "Coffee stand", "waiting milk dog_access"),
        p("coffee_tea_sweets", "Coffee lounge", "laptop outlets dog_access"),
        p("coffee_tea_sweets", "Roastery", "beans tasting dog_access"),
        p("coffee_tea_sweets", "Tea house", "noise outdoor_seating dog_access"),
        p("coffee_tea_sweets", "Tea store", "tasting gift_packaging dog_access"),
        p("coffee_tea_sweets", "Juice shop", "juice dog_access waiting"),
        p("coffee_tea_sweets", "Smoothie shop", "milk dog_access waiting"),
        p("coffee_tea_sweets", "Acai", "dietary_menu dog_access seating"),
        p("coffee_tea_sweets", "Bakery", "dog_access dietary_menu seating"),
        p("coffee_tea_sweets", "Bagel shop", "dog_access seating waiting"),
        p("coffee_tea_sweets", "Donut shop", "dog_access waiting dietary_menu"),
        p("coffee_tea_sweets", "Cake shop", "dog_access gift_packaging everyday_staff_help"),
        p("coffee_tea_sweets", "Pastry shop", "dog_access seating dietary_menu"),
        p("coffee_tea_sweets", "Dessert shop", "dog_access takeaway dietary_menu"),
        p("coffee_tea_sweets", "Dessert restaurant", "dog_access sharing booking_ease"),
        // Gelato and ice cream need the same dog-access, dietary and seating facts.
        p("coffee_tea_sweets", "Ice cream|Gelato", "dog_access frozen_treat seating"),
        p("coffee_tea_sweets", "Candy store", "dog_access tasting gift_packaging"),
        p("coffee_tea_sweets", "Chocolate shop", "dog_access tasting gift_packaging"),
        p("coffee_tea_sweets", "Chocolate factory", "guided_tour tasting dog_access"),
        p("coffee_tea_sweets", "Chocolate lounge", "tasting seating dog_access"),
        // Broad confectionery names do not establish whether baked goods exist.
        p("coffee_tea_sweets", "Confectionery", "dog_access tasting gift_packaging"),
        p("coffee_tea_sweets", "Cat cafe", "resident_animals booking_ease dog_access"),
        p("coffee_tea_sweets", "Dog cafe", "dog_access outdoor_seating resident_animals"),

        p("bars_nightlife", "Bar", "noise alcohol_free dog_access"),
        p("bars_nightlife", "Cocktail bar", "cocktails alcohol_free booking_ease"),
        p("bars_nightlife", "Pub", "dog_access food_at_bar noise"),
        p("bars_nightlife", "Irish pub", "live_music food_at_bar dog_access"),
        p("bars_nightlife", "Billiards", "games game_payment noise"),
        p("bars_nightlife", "Sports bar", "screens booking_ease food_at_bar"),
        p("bars_nightlife", "Wine bar", "wine_by_glass dog_access noise"),
        p("bars_nightlife", "Cider bar", "cider noise food_at_bar"),
        p("bars_nightlife", "Sake bar", "sake food_at_bar noise"),
        p("bars_nightlife", "Game bar", "games game_payment alcohol_free"),
        p("bars_nightlife", "Gastropub", "dog_access beer_selection noise"),
        p("bars_nightlife", "Bar & grill", "dog_access screens outdoor_seating"),
        p("bars_nightlife", "Dance hall", "dancing live_music coat_storage"),
        // Club/nightclub/disco describe the same entry, dance and belongings needs.
        p("bars_nightlife", "Club|Disco|Nightclub", "door dancing coat_storage"),
        p("bars_nightlife", "Lounge", "noise booking_ease cocktails"),
        p("bars_nightlife", "Hookah bar", "smoking_area ventilation alcohol_free"),
        p("bars_nightlife", "Beer garden", "outdoor_seating shade dog_access"),
        p("bars_nightlife", "Jazz club", "show_seating acoustics door"),
        p("bars_nightlife", "Hi-fi lounge", "acoustics noise booking_ease"),
        p("bars_nightlife", "Brewery", "beer_selection tasting dog_access"),
        p("bars_nightlife", "Brewpub", "beer_selection food_at_bar dog_access"),
        p("bars_nightlife", "Winery", "tasting booking_ease dog_access"),
        p("bars_nightlife", "Vineyard", "vineyard tasting dog_access"),
        p("bars_nightlife", "Karaoke", "karaoke booking_ease noise"),
        p("bars_nightlife", "Live music", "acoustics show_seating door"),
        p("bars_nightlife", "Comedy club", "show_seating sightlines door"),
        p("bars_nightlife", "Casino", "smoking_area food_at_bar coat_storage"),
        p("bars_nightlife", "Distillery", "distillery tasting booking_ease"),

        p("outdoors_nature", "Park", "leash shade restroom"),
        p("outdoors_nature", "City park", "leash shade seating"),
        p("outdoors_nature", "State park", "leash restroom admission"),
        p("outdoors_nature", "National park", "leash visitor_info admission"),
        p("outdoors_nature", "Hiking area", "leash incline trail_marking"),
        // A hike and a trail both describe the route underfoot.
        p("outdoors_nature", "Trail|Hike", "leash incline trail_marking"),
        p("outdoors_nature", "Beach", "leash shade beach_rinse"),
        p("outdoors_nature", "Dog beach", "leash beach_rinse beach_access"),
        p("outdoors_nature", "Lake", "leash shade restroom"),
        p("outdoors_nature", "River", "leash water_edge shade"),
        p("outdoors_nature", "Island", "leash shelter ferry_access"),
        p("outdoors_nature", "Woods/forest", "leash trail_marking path_surface"),
        p("outdoors_nature", "Mountain peak", "leash incline shelter"),
        p("outdoors_nature", "Scenic spot", "leash view_access shade"),
        // Viewpoint and overlook are alternative names for the same viewing stop.
        p("outdoors_nature", "Viewpoint|Overlook", "leash view_access seating"),
        p("outdoors_nature", "Waterfall", "leash view_access incline"),
        p("outdoors_nature", "Hot spring", "leash hot_spring changing"),
        p("outdoors_nature", "Cave", "leash cave booking_policy"),
        p("outdoors_nature", "Nature preserve", "leash trail_marking wildlife_viewing"),
        p("outdoors_nature", "Wildlife refuge", "leash path_surface shade"),
        p("outdoors_nature", "Wildlife park", "leash animal_paths admission"),
        p("outdoors_nature", "Botanical garden", "leash path_surface shade"),
        p("outdoors_nature", "Garden", "leash shade restroom"),
        p("outdoors_nature", "Picnic area", "leash shade picnic"),
        p("outdoors_nature", "Dog park", "fenced leash water_refill"),
        p("outdoors_nature", "Playground", "playground_age fenced shade"),
        p("outdoors_nature", "Campground", "leash camp_toilet camp_booking"),
        p("outdoors_nature", "RV park", "leash camp_power camp_toilet"),
        p("outdoors_nature", "Dispersed camping", "leash camp_toilet offroad"),
        // Accommodation questions stay consistent when the same type is saved
        // under Outdoors or Stays; no public-bathroom claim for a private cabin.
        p("outdoors_nature", "Cabin", "dog_access everyday_kitchen everyday_room_cooling"),
        p("outdoors_nature", "Cottage", "dog_access everyday_kitchen everyday_parking"),
        p("outdoors_nature", "Marina", "leash restroom arrival_parking"),
        p("outdoors_nature", "Fishing pier", "leash seating shade"),
        p("outdoors_nature", "Fishing pond", "leash fishing_gear shade"),
        p("outdoors_nature", "Fishing charter", "fishing_gear restroom booking_ease"),
        p("outdoors_nature", "Ski resort", "leash ski_rental ski_levels"),
        p("outdoors_nature", "Cycling park", "leash bike_trails water_refill"),
        p("outdoors_nature", "Skate park", "leash skate_features activity_lights"),
        p("outdoors_nature", "Off-roading area", "leash offroad shelter"),
        p("outdoors_nature", "Adventure sports", "adventure_guidance equipment booking_ease"),

        p("things_to_do", "Tourist attraction", "admission visit_time step_free"),
        p("things_to_do", "Landmark", "interpretation view_access visit_time"),
        // Historical place/landmark differ in naming, not visitor logistics.
        p("things_to_do", "Historical place|Historical landmark", "interpretation guided_tour step_free"),
        p("things_to_do", "Monument", "interpretation view_access seating"),
        p("things_to_do", "Sculpture", "interpretation photography step_free"),
        p("things_to_do", "Fountain", "seating shade photography"),
        p("things_to_do", "Castle", "guided_tour incline admission"),
        p("things_to_do", "Plaza|Town square", "seating shade restroom"),
        p("things_to_do", "Visitor center", "visitor_info restroom step_free"),
        p("things_to_do", "Museum", "exhibits visit_time admission"),
        p("things_to_do", "Art museum", "exhibits photography seating"),
        p("things_to_do", "History museum", "interpretation guided_tour visit_time"),
        p("things_to_do", "Art gallery", "exhibits photography admission"),
        p("things_to_do", "Art studio", "art_classes equipment booking"),
        p("things_to_do", "Cultural landmark", "interpretation guided_tour photography"),
        p("things_to_do", "Cultural center", "art_classes visitor_info admission"),
        p("things_to_do", "Theater|Performing arts theater", "sightlines show_seating step_free"),
        p("things_to_do", "Concert hall|Philharmonic hall", "acoustics show_seating coat_storage"),
        p("things_to_do", "Opera house", "sightlines acoustics coat_storage"),
        p("things_to_do", "Amphitheater", "sightlines shade show_seating"),
        p("things_to_do", "Auditorium", "acoustics sightlines step_free"),
        p("things_to_do", "Movie theater", "screen_comfort sightlines cinema_snacks"),
        p("things_to_do", "Planetarium", "show_seating admission visit_time"),
        p("things_to_do", "Observation deck", "view_indoor waiting view_access"),
        p("things_to_do", "Aquarium", "hands_on animal_paths admission"),
        p("things_to_do", "Zoo", "animal_paths shade restroom"),
        p("things_to_do", "Amusement park", "ride_queues ride_storage ride_restrictions"),
        p("things_to_do", "Water park", "ride_storage changing ride_restrictions"),
        p("things_to_do", "Ferris wheel", "ride_queues ride_cabin admission"),
        p("things_to_do", "Roller coaster", "ride_queues ride_storage ride_restrictions"),
        p("things_to_do", "Arcade", "game_payment games noise"),
        p("things_to_do", "Bowling", "booking equipment game_payment"),
        p("things_to_do", "Mini golf", "game_payment shade equipment"),
        p("things_to_do", "Billiards", "games game_payment equipment"),
        p("things_to_do", "Darts", "equipment games group_tables"),
        p("things_to_do", "Axe throwing", "instruction equipment booking"),
        p("things_to_do", "Board game lounge", "board_games game_payment food_at_bar"),
        p("things_to_do", "Go-karting", "ride_restrictions equipment ride_queues"),
        p("things_to_do", "Paintball", "equipment instruction changing"),
        p("things_to_do", "Indoor playground", "indoor_play seating restroom"),
        p("things_to_do", "Event venue", "event_layout event_food step_free"),
        p("things_to_do", "Convention center", "everyday_wayfinding everyday_charging step_free"),
        p("things_to_do", "Banquet hall", "event_food group_tables step_free"),
        p("things_to_do", "Wedding venue", "event_layout event_food outdoor_seating"),
        p("things_to_do", "Community center", "visitor_info event_layout step_free"),
        p("things_to_do", "Internet cafe", "wifi outlets noise"),
        p("things_to_do", "Dance hall", "dancing group_instruction changing"),
        p("things_to_do", "Barbecue area", "barbecue_setup picnic shade"),

        p("wellness_fitness", "Gym", "fitness_dropin gym_equipment changing"),
        // Provider "fitness center" does not establish that classes exist.
        // Treat this broad label as equivalent to Gym, not a coached studio.
        p("wellness_fitness", "Fitness center", "fitness_dropin gym_equipment changing"),
        p("wellness_fitness", "Yoga studio", "yoga_style class_busyness booking_ease"),
        p("wellness_fitness", "Pilates studio", "pilates_reformer class_busyness booking_ease"),
        p("wellness_fitness", "CrossFit gym", "crossfit_scaling crossfit_format fitness_dropin"),
        p("wellness_fitness", "Functional fitness studio", "functional_format coaching venue_busyness"),
        p("wellness_fitness", "Wellness studio", "booking_ease equipment changing_privacy"),
        p("wellness_fitness", "Wellness center", "treatment_booking changing_privacy step_free"),
        p("wellness_fitness", "Sports club", "fitness_dropin court_booking changing"),
        p("wellness_fitness", "Sports complex", "court_booking changing visitor_info"),
        p("wellness_fitness", "Sports coaching", "coaching group_instruction equipment"),
        p("wellness_fitness", "Sports school", "group_instruction instruction equipment"),
        p("wellness_fitness", "Athletic field", "field_surface activity_lights restroom"),
        p("wellness_fitness", "Swimming pool", "pool_use pool_setting changing"),
        p("wellness_fitness", "Tennis court", "tennis_surface court_booking court_lights"),
        p("wellness_fitness", "Golf course", "golf golf_hire booking"),
        p("wellness_fitness", "Indoor golf", "golf_simulator golf_hire booking"),
        p("wellness_fitness", "Ice skating rink", "ice_sessions equipment ride_storage"),
        p("wellness_fitness", "Volleyball court", "volleyball_surface volleyball_net court_booking"),
        p("wellness_fitness", "Soccer field", "field_surface field_goals activity_lights"),
        p("wellness_fitness", "Basketball court", "basketball court_booking court_lights"),
        p("wellness_fitness", "Pickleball court", "pickleball_lines court_booking court_lights"),
        p("wellness_fitness", "Spa", "treatment_booking changing_privacy sauna"),
        p("wellness_fitness", "Massage", "massage privacy treatment_booking"),
        p("wellness_fitness", "Massage spa", "massage changing_privacy treatment_booking"),
        p("wellness_fitness", "Sauna", "sauna changing_privacy booking"),
        p("wellness_fitness", "Chiropractor", "treatment_booking treatment_info privacy"),
        // Care questions cover facility logistics only; never diagnoses, medical
        // effectiveness or a person's reason for visiting. Equivalent care
        // labels intentionally share practical arrival/appointment questions.
        p("wellness_fitness", "Dentist|Dental clinic", "treatment_booking treatment_info step_free"),
        p("wellness_fitness", "Optometrist", "eye_shop treatment_booking step_free"),
        p("wellness_fitness", "Ophthalmologist", "treatment_booking treatment_info step_free"),
        p("wellness_fitness", "Eye care center", "eye_shop treatment_booking waiting"),
        p("wellness_fitness", "Doctor|Dermatologist", "treatment_booking privacy step_free"),
        p("wellness_fitness", "Pediatrician", "waiting everyday_baby_changing step_free"),
        p("wellness_fitness", "Urgent care", "waiting treatment_booking arrival_parking"),
        p("wellness_fitness", "Medical clinic", "treatment_booking waiting step_free"),
        p("wellness_fitness", "Medical center", "visitor_info arrival_parking step_free"),
        p("wellness_fitness", "Hospital", "visitor_info arrival_parking restroom"),
        p("wellness_fitness", "Medical lab", "lab_booking treatment_info waiting"),
        p("wellness_fitness", "Pharmacy|Drugstore", "pharmacy waiting step_free"),
        p("wellness_fitness", "Physiotherapist|Physical therapy", "rehab_space privacy step_free"),
        p("wellness_fitness", "Foot care|Podiatrist", "treatment_booking privacy step_free"),
        p("wellness_fitness", "Veterinary care", "vet_wait treatment_booking arrival_parking"),
        p("wellness_fitness", "Mental health/therapy", "privacy treatment_booking step_free"),
        p("wellness_fitness", "Retreat", "retreat dietary_menu step_free"),

        p("outdoors_nature", "Surf", "surf_rental venue_busyness leash"),
        p("outdoors_nature", "Surf break", "surf_crowding beach_rinse leash"),
        p("outdoors_nature", "Kayak/canoe rental", "equipment booking_ease dogs_on_boats"),
        p("things_to_do", "Stadium", "seat_cover show_seating everyday_bag_check"),
        p("things_to_do", "Arena", "acoustics show_seating everyday_bag_check"),
        p("wellness_fitness", "Beach tennis", "court_booking equipment court_lights"),
        p("wellness_fitness", "Beach volleyball", "volleyball_net court_booking shade"),
        p("wellness_fitness", "Padel court", "court_booking court_setting equipment"),
        p("wellness_fitness", "Climbing gym", "climbing_type equipment venue_busyness"),
        p("wellness_fitness", "Surf school", "equipment class_busyness booking_ease"),

        p("place", "Place", "step_free seating restroom")
    ]

    private static func p(_ category: String, _ subtypes: String, _ questions: String) -> PlaceCheckInQuestionProfile {
        PlaceCheckInQuestionProfile(
            categoryID: category,
            subcategories: subtypes.components(separatedBy: "|"),
            questionIDs: questions.components(separatedBy: " ")
        )
    }
}
