import Foundation

/// Reviewed binary prompts coexist with historical options. Never infer a Yes
/// from a legacy choice: old answers retain their original, qualified meaning.
enum PlaceCheckInBinaryPrompts {
    struct Spec: Equatable, Sendable {
        let prompt: String
        let positiveTerms: [String]
    }
    static let specs: [String: Spec] = [
        "place_detail_class_busyness": Spec(prompt: "Was the class busy?", positiveTerms: ["busy class"]),
        "place_detail_booking_ease": Spec(prompt: "Easy to book?", positiveTerms: ["easy booking"]),
        "place_detail_venue_busyness": Spec(prompt: "Was it busy?", positiveTerms: ["busy place"]),
        "place_detail_surf_rental": Spec(prompt: "Surfboard rental available?", positiveTerms: ["surfboard rental"]),
        "place_detail_surf_crowding": Spec(prompt: "Crowded in the water?", positiveTerms: ["crowded surf break"]),
        "place_detail_booking_policy": Spec(prompt: "Reservation required?", positiveTerms: ["reservation required"]),
        "place_detail_waiting": Spec(prompt: "Long wait?", positiveTerms: ["long wait"]),
        "place_detail_step_free": Spec(prompt: "Step-free entrance?", positiveTerms: ["step free entrance"]),
        "place_detail_restroom": Spec(prompt: "Bathroom available?", positiveTerms: ["bathroom"]),
        "place_detail_seating": Spec(prompt: "Somewhere to sit?", positiveTerms: ["seating"]),
        "place_detail_noise": Spec(prompt: "Easy to have a conversation?", positiveTerms: ["easy conversation"]),
        "place_detail_outdoor_seating": Spec(prompt: "Outdoor seating?", positiveTerms: ["outdoor seating"]),
        "place_detail_outlets": Spec(prompt: "Power outlets?", positiveTerms: ["power outlets"]),
        "place_detail_wifi": Spec(prompt: "Did the Wi-Fi work well?", positiveTerms: ["reliable wifi"]),
        "place_detail_dog_access": Spec(prompt: "Dogs allowed?", positiveTerms: ["dogs allowed"]),
        "place_detail_shade": Spec(prompt: "Shaded areas?", positiveTerms: ["shade"]),
        "place_detail_takeaway": Spec(prompt: "Takeaway available?", positiveTerms: ["takeaway"]),
        "place_detail_vegetarian": Spec(prompt: "Vegetarian meal options?", positiveTerms: ["vegetarian options"]),
        "place_detail_vegan": Spec(prompt: "Vegan meal options?", positiveTerms: ["vegan options"]),
        "place_detail_sharing": Spec(prompt: "Good for sharing?", positiveTerms: ["sharing plates"]),
        "place_detail_group_tables": Spec(prompt: "Room for a group?", positiveTerms: ["group seating"]),
        "place_detail_spice": Spec(prompt: "Could you choose the spice level?", positiveTerms: ["adjustable spice"]),
        "place_detail_counter_seating": Spec(prompt: "Counter seating?", positiveTerms: ["counter seating"]),
        "place_detail_alcohol_free": Spec(prompt: "Good alcohol-free options?", positiveTerms: ["alcohol free options"]),
        "place_detail_dietary_menu": Spec(prompt: "Clear dietary information?", positiveTerms: ["dietary information"]),
        "place_detail_table_cooking": Spec(prompt: "Cook at the table?", positiveTerms: ["table cooking"]),
        "place_detail_ventilation": Spec(prompt: "Smoky inside?", positiveTerms: ["smoky indoors"]),
        "place_detail_pizza": Spec(prompt: "Pizza by the slice?", positiveTerms: ["pizza by the slice"]),
        "place_detail_wine_by_glass": Spec(prompt: "Wine by the glass?", positiveTerms: ["wine by the glass"]),
        "place_detail_gluten_menu": Spec(prompt: "Clear gluten-free information?", positiveTerms: ["gluten free information"]),
        "place_detail_halal_menu": Spec(prompt: "Clear halal information?", positiveTerms: ["halal information"]),
        "place_detail_laptop": Spec(prompt: "Laptops welcome?", positiveTerms: ["laptop friendly"]),
        "place_detail_beans": Spec(prompt: "Beans to take home?", positiveTerms: ["coffee beans"]),
        "place_detail_milk": Spec(prompt: "Milk alternatives?", positiveTerms: ["milk alternatives"]),
        "place_detail_juice": Spec(prompt: "Made-to-order juice?", positiveTerms: ["fresh juice"]),
        "place_detail_frozen_treat": Spec(prompt: "Dairy-free frozen treats?", positiveTerms: ["dairy free ice cream"]),
        "place_detail_gift_packaging": Spec(prompt: "Gift packaging?", positiveTerms: ["gift packaging"]),
        "place_detail_tasting": Spec(prompt: "Samples or tastings?", positiveTerms: ["tastings"]),
        "place_detail_resident_animals": Spec(prompt: "Entry fee to visit the animals?", positiveTerms: ["animal cafe entry fee"]),
        "place_detail_screens": Spec(prompt: "Good screens for watching sports?", positiveTerms: ["sports screens"]),
        "place_detail_live_music": Spec(prompt: "Live music on your visit?", positiveTerms: ["live music"]),
        "place_detail_dancing": Spec(prompt: "Room to dance?", positiveTerms: ["dance floor"]),
        "place_detail_door": Spec(prompt: "Cover charge or ticket required?", positiveTerms: ["cover charge"]),
        "place_detail_coat_storage": Spec(prompt: "Coat storage?", positiveTerms: ["coat storage"]),
        "place_detail_food_at_bar": Spec(prompt: "Food with drinks?", positiveTerms: ["bar food"]),
        "place_detail_smoking_area": Spec(prompt: "Separate smoking area?", positiveTerms: ["separate smoking area"]),
        "place_detail_vineyard": Spec(prompt: "Can you explore the vineyard?", positiveTerms: ["vineyard access"]),
        "place_detail_water_refill": Spec(prompt: "Drinking-water refill?", positiveTerms: ["drinking water refill"]),
        "place_detail_trail_marking": Spec(prompt: "Easy to follow the trail?", positiveTerms: ["marked trail"]),
        "place_detail_picnic": Spec(prompt: "Picnic spots?", positiveTerms: ["picnic area"]),
        "place_detail_beach_rinse": Spec(prompt: "Rinse-off showers?", positiveTerms: ["beach showers"]),
        "place_detail_beach_access": Spec(prompt: "Easy route down to the beach?", positiveTerms: ["easy beach access"]),
        "place_detail_lifeguard": Spec(prompt: "Lifeguards on duty during your visit?", positiveTerms: ["lifeguards on visit"]),
        "place_detail_shelter": Spec(prompt: "Shelter from the weather?", positiveTerms: ["weather shelter"]),
        "place_detail_fenced": Spec(prompt: "Was the play area fully fenced?", positiveTerms: ["fenced play area"]),
        "place_detail_camp_toilet": Spec(prompt: "Campsite toilets?", positiveTerms: ["camp toilets"]),
        "place_detail_camp_surface": Spec(prompt: "Was your pitch level?", positiveTerms: ["level campsite"]),
        "place_detail_kitchen": Spec(prompt: "Cooking facilities?", positiveTerms: ["cooking facilities"]),
        "place_detail_fishing_gear": Spec(prompt: "Fishing gear available?", positiveTerms: ["fishing gear available"]),
        "place_detail_ski_rental": Spec(prompt: "Ski rental nearby?", positiveTerms: ["ski rental"]),
        "place_detail_admission": Spec(prompt: "Entry fee?", positiveTerms: ["paid admission"]),
        "place_detail_interpretation": Spec(prompt: "Signs explaining the place?", positiveTerms: ["interpretive signs"]),
        "place_detail_guided_tour": Spec(prompt: "Guided tours available?", positiveTerms: ["guided tours"]),
        "place_detail_hands_on": Spec(prompt: "Hands-on activities?", positiveTerms: ["hands on activities"]),
        "place_detail_art_classes": Spec(prompt: "Art activities or workshops?", positiveTerms: ["art workshops"]),
        "place_detail_sightlines": Spec(prompt: "Clear view from your spot?", positiveTerms: ["clear sightlines"]),
        "place_detail_acoustics": Spec(prompt: "Was the sound good?", positiveTerms: ["good acoustics"]),
        "place_detail_screen_comfort": Spec(prompt: "Comfortable cinema seats?", positiveTerms: ["comfortable cinema seats"]),
        "place_detail_cinema_snacks": Spec(prompt: "Food sold for the film?", positiveTerms: ["cinema food"]),
        "place_detail_ride_queues": Spec(prompt: "Long waits for rides?", positiveTerms: ["long ride waits"]),
        "place_detail_ride_storage": Spec(prompt: "Storage during the activity?", positiveTerms: ["activity storage"]),
        "place_detail_ride_restrictions": Spec(prompt: "Clear height or age requirements?", positiveTerms: ["posted activity requirements"]),
        "place_detail_equipment": Spec(prompt: "Equipment available?", positiveTerms: ["equipment available"]),
        "place_detail_instruction": Spec(prompt: "Lessons or instruction available?", positiveTerms: ["lessons available"]),
        "place_detail_indoor_play": Spec(prompt: "Separate play areas by age?", positiveTerms: ["separate child play areas"]),
        "place_detail_barbecue_setup": Spec(prompt: "Grills available?", positiveTerms: ["barbecue grills"]),
        "place_detail_fitness_dropin": Spec(prompt: "Day pass available?", positiveTerms: ["gym day pass"]),
        "place_detail_changing": Spec(prompt: "Showers available?", positiveTerms: ["showers"]),
        "place_detail_crossfit_scaling": Spec(prompt: "Were workout adaptations explained?", positiveTerms: ["crossfit scaling explained"]),
        "place_detail_coaching": Spec(prompt: "Did coaches give technique feedback?", positiveTerms: ["technique coaching"]),
        "place_detail_court_lights": Spec(prompt: "Court lights on for evening play?", positiveTerms: ["lit courts"]),
        "place_detail_activity_lights": Spec(prompt: "Lit for evening use on your visit?", positiveTerms: ["activity area lit on visit"]),
        "place_detail_volleyball_net": Spec(prompt: "Volleyball net ready to use?", positiveTerms: ["volleyball net provided"]),
        "place_detail_pickleball_lines": Spec(prompt: "Dedicated pickleball courts?", positiveTerms: ["dedicated pickleball courts"]),
        "place_detail_field_goals": Spec(prompt: "Goals already set up?", positiveTerms: ["goals provided"]),
        "place_detail_golf_hire": Spec(prompt: "Club rental available?", positiveTerms: ["golf club rental"]),
        "place_detail_privacy": Spec(prompt: "Private appointment room?", positiveTerms: ["private appointment room"]),
        "place_detail_treatment_info": Spec(prompt: "Clear instructions before the visit?", positiveTerms: ["clear appointment instructions"]),
        "place_detail_massage": Spec(prompt: "Could you choose the massage pressure?", positiveTerms: ["custom massage pressure"]),
        "place_detail_eye_shop": Spec(prompt: "Eyewear to try on?", positiveTerms: ["eyewear selection"]),
        "place_detail_pharmacy": Spec(prompt: "Prescription ready on arrival?", positiveTerms: ["prescription ready on arrival"]),
        "place_detail_rehab_space": Spec(prompt: "Space for guided exercises?", positiveTerms: ["rehab exercise area"]),
        "place_detail_vet_wait": Spec(prompt: "Separate animal waiting areas?", positiveTerms: ["separate pet waiting areas"]),
        "place_detail_changing_privacy": Spec(prompt: "Private changing space?", positiveTerms: ["private changing cubicles"]),
        "place_detail_arrival_parking": Spec(prompt: "Easy to find parking?", positiveTerms: ["easy parking"]),
        "place_detail_visitor_info": Spec(prompt: "Visitor information available?", positiveTerms: ["visitor information"]),
        "place_detail_everyday_product_testers": Spec(prompt: "Testers or samples available?", positiveTerms: ["product samples"]),
        "place_detail_everyday_schedule": Spec(prompt: "Did the service start on time?", positiveTerms: ["service on time on visit"]),
        "place_detail_everyday_atm_fee": Spec(prompt: "Was the withdrawal fee clear?", positiveTerms: ["withdrawal fee clear"]),
        "place_detail_everyday_cash_withdrawal": Spec(prompt: "Could you withdraw cash?", positiveTerms: ["cash withdrawal worked on visit"]),
        "place_detail_everyday_bike_availability": Spec(prompt: "Bikes available when you arrived?", positiveTerms: ["bikes available on visit"]),
        "place_detail_everyday_baby_changing": Spec(prompt: "Baby-changing table?", positiveTerms: ["baby changing table"]),
        "place_detail_everyday_prices": Spec(prompt: "Clear prices before paying?", positiveTerms: ["clear prices"]),
        "place_detail_everyday_staff_help": Spec(prompt: "Help choosing available?", positiveTerms: ["choosing help available"]),
        "place_detail_everyday_fitting": Spec(prompt: "Somewhere to try things on?", positiveTerms: ["trying on area"]),
        "place_detail_everyday_loading": Spec(prompt: "Space to load or unload?", positiveTerms: ["loading area"]),
        "place_detail_everyday_parking": Spec(prompt: "Easy to find parking?", positiveTerms: ["easy parking"]),
        "place_detail_everyday_repair": Spec(prompt: "Repairs offered?", positiveTerms: ["repairs offered"]),
        "place_detail_everyday_refill": Spec(prompt: "Refill your own containers?", positiveTerms: ["container refills"]),
        "place_detail_everyday_gift_wrap": Spec(prompt: "Gift wrapping offered?", positiveTerms: ["gift wrapping"]),
        "place_detail_everyday_quote": Spec(prompt: "Cost explained before work began?", positiveTerms: ["clear quote"]),
        "place_detail_everyday_instructions": Spec(prompt: "Clear instructions?", positiveTerms: ["clear instructions"]),
        "place_detail_everyday_machines": Spec(prompt: "Machines available on arrival?", positiveTerms: ["machines available"]),
        "place_detail_everyday_supplies": Spec(prompt: "Supplies provided?", positiveTerms: ["supplies provided"]),
        "place_detail_everyday_wayfinding": Spec(prompt: "Easy to find your way?", positiveTerms: ["easy navigation"]),
        "place_detail_everyday_waiting_space": Spec(prompt: "Somewhere to wait?", positiveTerms: ["waiting area"]),
        "place_detail_everyday_shelter": Spec(prompt: "Shelter while waiting?", positiveTerms: ["covered waiting area"]),
        "place_detail_everyday_luggage": Spec(prompt: "Luggage storage?", positiveTerms: ["luggage storage"]),
        "place_detail_everyday_boarding": Spec(prompt: "Step-free route to boarding?", positiveTerms: ["step free boarding"]),
        "place_detail_everyday_charging": Spec(prompt: "Phone charging?", positiveTerms: ["phone charging"]),
        "place_detail_everyday_charger_use": Spec(prompt: "Could you start charging?", positiveTerms: ["charging worked on visit"]),
        "place_detail_everyday_water": Spec(prompt: "Water refill?", positiveTerms: ["water refill"]),
        "place_detail_everyday_showers": Spec(prompt: "Showers available?", positiveTerms: ["showers"]),
        "place_detail_everyday_laundry": Spec(prompt: "Laundry available?", positiveTerms: ["laundry"]),
        "place_detail_everyday_room_noise": Spec(prompt: "Quiet room when you rested?", positiveTerms: ["quiet room"]),
        "place_detail_everyday_room_cooling": Spec(prompt: "Room temperature controls?", positiveTerms: ["room temperature controls"]),
        "place_detail_everyday_kitchen": Spec(prompt: "Guest cooking facilities?", positiveTerms: ["guest kitchen"]),
        "place_detail_everyday_breakfast": Spec(prompt: "Breakfast included?", positiveTerms: ["breakfast included"]),
        "place_detail_everyday_hookups": Spec(prompt: "Power at your pitch?", positiveTerms: ["electric hookup"]),
        "place_detail_everyday_desk": Spec(prompt: "Somewhere to work?", positiveTerms: ["workspace"]),
        "place_detail_everyday_quiet_work": Spec(prompt: "Quiet place to concentrate?", positiveTerms: ["quiet workspace"]),
        "place_detail_everyday_day_access": Spec(prompt: "Day or session pass?", positiveTerms: ["day pass"]),
        "place_detail_everyday_study_rooms": Spec(prompt: "Separate study or meeting rooms?", positiveTerms: ["meeting rooms"]),
        "place_detail_everyday_printing": Spec(prompt: "Visitor printing?", positiveTerms: ["printing"]),
        "place_detail_everyday_visitor_guidance": Spec(prompt: "Clear visitor rules?", positiveTerms: ["visitor rules"]),
        "place_detail_everyday_bag_check": Spec(prompt: "Bag checks on entry?", positiveTerms: ["bag checks"]),
        "place_detail_everyday_rest_seats": Spec(prompt: "Seating without a purchase?", positiveTerms: ["public seating"]),
        "place_detail_everyday_crossing": Spec(prompt: "Marked crossing or bridge?", positiveTerms: ["marked crossing"]),
        "place_detail_everyday_pedestrian_route": Spec(prompt: "Walking path separate from traffic?", positiveTerms: ["separate walking path"]),
        "place_detail_everyday_tire_air": Spec(prompt: "Tire air pump?", positiveTerms: ["tire air pump"]),
        "place_detail_everyday_restroom_fee": Spec(prompt: "Toilet fee?", positiveTerms: ["paid toilet"]),
        "place_detail_everyday_handwashing": Spec(prompt: "Handwashing facilities?", positiveTerms: ["handwashing"]),
        "place_detail_everyday_changing": Spec(prompt: "Private changing space?", positiveTerms: ["private changing space"]),
        "place_detail_everyday_lockers": Spec(prompt: "Lockers available?", positiveTerms: ["lockers"]),
        "place_detail_everyday_horse_equipment": Spec(prompt: "Riding equipment available?", positiveTerms: ["riding equipment"]),
    ]
}
