import Foundation

extension PlaceCheckInQuestionCatalog {
    /// Each row is a deliberate subtype selection. Shared cuisine rows reflect
    /// equivalent practical dining needs, not assumed dishes or national traits.
    /// Specialized formats below get their own questions when the format itself
    /// gives us reliable context. A nationality never implies spice or a diet.
    static let coreProfiles: [PlaceCheckInQuestionProfile] = [
        p("restaurants_food", "Restaurant", "booking noise vegetarian"),
        p("restaurants_food", "Thai", "spice vegetarian sharing"),
        p("restaurants_food", "Vietnamese", "fresh_herbs vegetarian takeaway"),
        p("restaurants_food", "Chinese", "sharing group_tables menu_guidance"),
        p("restaurants_food", "Korean", "sharing vegetarian menu_guidance"),
        p("restaurants_food", "Japanese", "set_menu counter_seating vegetarian"),
        p("restaurants_food", "Indian", "spice vegetarian sharing"),
        p("restaurants_food", "Asian fusion", "small_plates dietary_menu noise"),
        p("restaurants_food", "Sushi", "sushi_menu counter_seating booking"),
        p("restaurants_food", "Ramen", "broth noodles waiting"),
        p("restaurants_food", "Dumplings", "dumplings vegetarian takeaway"),
        p("restaurants_food", "Bao buns", "bao vegetarian seating"),
        p("restaurants_food", "Noodles", "noodles vegetarian portions"),
        p("restaurants_food", "Dim sum", "dim_sum sharing waiting"),
        p("restaurants_food", "Hot pot", "hotpot broth ventilation"),
        p("restaurants_food", "Cantonese", "sharing group_tables menu_guidance"),
        p("restaurants_food", "Taiwanese", "menu_guidance vegetarian takeaway"),
        p("restaurants_food", "Izakaya", "small_plates noise booking"),
        p("restaurants_food", "Yakitori", "skewers counter_seating ventilation"),
        p("restaurants_food", "Yakiniku", "table_cooking ventilation booking"),
        p("restaurants_food", "North Indian|South Indian", "spice vegetarian sharing"),
        // Broad cuisine labels cannot tell us the actual menu. These rows keep
        // the same answerable choices instead of inventing regional dishes.
        p("restaurants_food", "Pakistani|Sri Lankan|Bangladeshi|Nepalese", "menu_guidance vegetarian sharing"),
        p("restaurants_food", "Malaysian|Singaporean|Indonesian|Filipino|Burmese|Cambodian|Laotian|Asian", "menu_guidance dietary_menu portions"),
        p("restaurants_food", "Tibetan|Mongolian|Georgian|Armenian|Uzbek", "sharing vegetarian menu_guidance"),
        p("restaurants_food", "Mongolian BBQ", "table_cooking service dietary_menu"),
        p("restaurants_food", "Korean BBQ", "table_cooking ventilation group_tables"),
        // Japanese BBQ and Yakiniku are equivalent dining formats.
        p("restaurants_food", "Japanese BBQ", "table_cooking ventilation booking"),
        p("restaurants_food", "Japanese curry", "curry spice counter_seating"),
        p("restaurants_food", "Tonkatsu", "set_menu crispy_takeaway counter_seating"),
        p("restaurants_food", "Afghan|Middle Eastern|Lebanese|Persian|Turkish|Israeli|Palestinian|Syrian|Iraqi|Jordanian|Yemeni", "shared_platter vegetarian menu_guidance"),
        p("restaurants_food", "Egyptian|Moroccan|Tunisian|Algerian", "menu_guidance sharing vegetarian"),
        p("restaurants_food", "Ethiopian|Eritrean", "shared_platter vegetarian service"),
        p("restaurants_food", "Somali|Kenyan|Nigerian|Ghanaian|Senegalese|South African|African", "menu_guidance portions vegetarian"),
        p("restaurants_food", "Falafel", "vegan dips takeaway"),
        p("restaurants_food", "Gyro", "portions takeaway seating"),
        p("restaurants_food", "Kebab", "grilled portions takeaway"),
        p("restaurants_food", "Shawarma", "portions service takeaway"),
        p("restaurants_food", "Halal", "halal_menu vegetarian group_tables"),
        p("restaurants_food", "Italian", "set_menu wine_by_glass booking"),
        p("restaurants_food", "Mediterranean", "vegetarian sharing outdoor_seating"),
        p("restaurants_food", "Greek", "sharing vegetarian outdoor_seating"),
        p("restaurants_food", "French", "set_menu wine_by_glass dinner_pace"),
        p("restaurants_food", "Spanish", "small_plates wine_by_glass dinner_pace"),
        p("restaurants_food", "Tapas", "tapas sharing counter_seating"),
        p("restaurants_food", "Portuguese|Basque", "menu_guidance dietary_menu booking"),
        p("restaurants_food", "German|Austrian|Bavarian|Swiss", "portions vegetarian group_tables"),
        p("restaurants_food", "Dutch|Belgian", "menu_guidance lunch vegetarian"),
        p("restaurants_food", "British|Irish", "lunch vegetarian noise"),
        p("restaurants_food", "Scandinavian|Swedish|Norwegian|Finnish|Danish", "menu_guidance set_menu vegetarian"),
        p("restaurants_food", "Polish|Ukrainian|Russian|Czech|Slovak|Hungarian|Romanian|Croatian|Serbian|Bosnian|Bulgarian|Albanian|Slovenian|Lithuanian|European|Eastern European", "menu_guidance portions vegetarian"),
        p("restaurants_food", "Pizza", "pizza waiting outdoor_seating"),
        p("restaurants_food", "Fish & chips", "crispy_takeaway portions seating"),
        p("restaurants_food", "Fondue", "fondue dietary_menu booking"),
        p("restaurants_food", "American|Canadian", "portions vegetarian group_tables"),
        p("restaurants_food", "Mexican", "spice vegetarian sharing"),
        p("restaurants_food", "Tex-Mex", "portions vegetarian salsa"),
        p("restaurants_food", "Caribbean|Jamaican|Puerto Rican|Dominican|Haitian|Panamanian|Cuban", "menu_guidance portions takeaway"),
        p("restaurants_food", "Brazilian|Argentinian|Colombian|Chilean|Peruvian|Venezuelan|Ecuadorian|Bolivian|Uruguayan|Salvadoran|Guatemalan|South American|Latin American", "menu_guidance sharing vegetarian"),
        p("restaurants_food", "Southwestern|Cajun", "spice vegetarian portions"),
        p("restaurants_food", "Californian", "dietary_menu outdoor_seating lunch"),
        p("restaurants_food", "Hawaiian", "portions takeaway menu_guidance"),
        p("restaurants_food", "Poke", "bowl dietary_menu takeaway"),
        p("restaurants_food", "Australian|New Zealand|Fijian|Samoan|Tongan", "menu_guidance portions sharing"),
        p("restaurants_food", "Burgers", "burger waiting outdoor_seating"),
        p("restaurants_food", "Diner", "breakfast counter_seating portions"),
        p("restaurants_food", "Hot dogs", "toppings seating takeaway"),
        p("restaurants_food", "Barbecue", "barbecue sharing outdoor_seating"),
        p("restaurants_food", "Wings", "wings spice group_tables"),
        p("restaurants_food", "Steakhouse", "steak booking wine_by_glass"),
        p("restaurants_food", "Bar & grill", "food_at_bar screens outdoor_seating"),
        p("restaurants_food", "Taco stand", "tacos salsa seating"),
        p("restaurants_food", "Taco truck", "tacos waiting seating"),
        p("restaurants_food", "Burrito", "portions vegetarian takeaway"),
        p("restaurants_food", "Taco", "tacos salsa vegetarian"),
        p("restaurants_food", "Sandwich", "sandwich waiting takeaway"),
        p("restaurants_food", "Bagel", "sandwich waiting seating"),
        p("restaurants_food", "Deli", "sandwich service lunch"),
        p("restaurants_food", "Salad", "bowl dietary_menu portions"),
        p("restaurants_food", "Bistro", "set_menu lunch noise"),
        p("restaurants_food", "Food court", "seating dietary_menu waiting"),
        p("restaurants_food", "Breakfast", "breakfast counter_seating waiting"),
        p("restaurants_food", "Brunch", "waiting booking outdoor_seating"),
        p("restaurants_food", "Soup", "soup vegetarian takeaway"),
        p("restaurants_food", "Chicken", "sharing portions crispy_takeaway"),
        p("restaurants_food", "Seafood", "seafood booking outdoor_seating"),
        p("restaurants_food", "Oyster bar", "oysters counter_seating wine_by_glass"),
        p("restaurants_food", "Vegetarian", "vegan dietary_menu portions"),
        p("restaurants_food", "Vegan", "dietary_menu portions takeaway"),
        p("restaurants_food", "Gluten-free", "gluten_menu dietary_menu takeaway"),
        p("restaurants_food", "Snack bar", "portions seating service"),
        p("restaurants_food", "Gastropub", "food_at_bar beer_selection noise"),

        p("coffee_tea_sweets", "Coffee shop", "laptop outlets dog_access"),
        p("coffee_tea_sweets", "Cafe", "laptop outdoor_seating dog_access"),
        p("coffee_tea_sweets", "Coffee stand", "waiting milk seating"),
        p("coffee_tea_sweets", "Coffee lounge", "outlets noise seating"),
        p("coffee_tea_sweets", "Roastery", "beans tasting seating"),
        p("coffee_tea_sweets", "Tea house", "tea noise seating"),
        p("coffee_tea_sweets", "Tea store", "tea_shop tasting gift_packaging"),
        p("coffee_tea_sweets", "Juice shop", "juice waiting seating"),
        p("coffee_tea_sweets", "Smoothie shop", "smoothie milk waiting"),
        p("coffee_tea_sweets", "Acai", "toppings portions seating"),
        p("coffee_tea_sweets", "Bakery", "bread pastry seating"),
        p("coffee_tea_sweets", "Bagel shop", "sandwich waiting seating"),
        p("coffee_tea_sweets", "Donut shop", "pastry waiting dietary_menu"),
        p("coffee_tea_sweets", "Cake shop", "cake gift_packaging takeaway"),
        p("coffee_tea_sweets", "Pastry shop", "pastry seating takeaway"),
        p("coffee_tea_sweets", "Dessert shop", "dessert takeaway dietary_menu"),
        p("coffee_tea_sweets", "Dessert restaurant", "dessert sharing booking"),
        // Gelato and ice cream need the same dietary, serving and seating facts.
        p("coffee_tea_sweets", "Ice cream|Gelato", "frozen_treat toppings seating"),
        p("coffee_tea_sweets", "Candy store", "gift_packaging dietary_menu tasting"),
        p("coffee_tea_sweets", "Chocolate shop", "gift_packaging tasting dietary_menu"),
        p("coffee_tea_sweets", "Chocolate factory", "guided_tour tasting gift_packaging"),
        p("coffee_tea_sweets", "Chocolate lounge", "tasting dessert seating"),
        // Broad confectionery names do not establish whether baked goods exist.
        p("coffee_tea_sweets", "Confectionery", "gift_packaging tasting dietary_menu"),
        p("coffee_tea_sweets", "Cat cafe", "resident_animals booking noise"),
        p("coffee_tea_sweets", "Dog cafe", "resident_animals dog_access outdoor_seating"),

        p("bars_nightlife", "Bar", "noise alcohol_free outdoor_seating"),
        p("bars_nightlife", "Cocktail bar", "cocktails alcohol_free booking"),
        p("bars_nightlife", "Pub", "food_at_bar beer_selection noise"),
        p("bars_nightlife", "Irish pub", "live_music food_at_bar beer_selection"),
        p("bars_nightlife", "Billiards", "games game_payment noise"),
        p("bars_nightlife", "Sports bar", "screens booking food_at_bar"),
        p("bars_nightlife", "Wine bar", "wine_by_glass small_plates noise"),
        p("bars_nightlife", "Cider bar", "cider noise food_at_bar"),
        p("bars_nightlife", "Sake bar", "sake small_plates noise"),
        p("bars_nightlife", "Game bar", "games game_payment alcohol_free"),
        p("bars_nightlife", "Gastropub", "food_at_bar beer_selection noise"),
        p("bars_nightlife", "Bar & grill", "food_at_bar screens outdoor_seating"),
        p("bars_nightlife", "Dance hall", "dancing live_music coat_storage"),
        // Club/nightclub/disco describe the same entry, dance and belongings needs.
        p("bars_nightlife", "Club|Disco|Nightclub", "door dancing coat_storage"),
        p("bars_nightlife", "Lounge", "noise booking cocktails"),
        p("bars_nightlife", "Hookah bar", "smoking_area ventilation alcohol_free"),
        p("bars_nightlife", "Beer garden", "outdoor_seating shade dog_access"),
        p("bars_nightlife", "Jazz club", "show_seating acoustics door"),
        p("bars_nightlife", "Hi-fi lounge", "acoustics noise booking"),
        p("bars_nightlife", "Brewery", "beer_selection tasting outdoor_seating"),
        p("bars_nightlife", "Brewpub", "beer_selection food_at_bar outdoor_seating"),
        p("bars_nightlife", "Winery", "tasting booking outdoor_seating"),
        p("bars_nightlife", "Vineyard", "vineyard tasting shade"),
        p("bars_nightlife", "Karaoke", "karaoke booking karaoke_charge"),
        p("bars_nightlife", "Live music", "acoustics show_seating door"),
        p("bars_nightlife", "Comedy club", "show_seating sightlines door"),
        p("bars_nightlife", "Casino", "smoking_area food_at_bar coat_storage"),
        p("bars_nightlife", "Distillery", "distillery tasting booking"),

        p("outdoors_nature", "Park", "shade restroom path_surface"),
        p("outdoors_nature", "City park", "shade seating picnic"),
        p("outdoors_nature", "State park", "admission trail_marking restroom"),
        p("outdoors_nature", "National park", "admission trail_marking visitor_info"),
        p("outdoors_nature", "Hiking area", "trail_marking incline water_refill"),
        // A hike and a trail both describe the route underfoot.
        p("outdoors_nature", "Trail|Hike", "trail_marking incline path_surface"),
        p("outdoors_nature", "Beach", "beach_rinse shade beach_access"),
        p("outdoors_nature", "Dog beach", "leash beach_rinse beach_access"),
        p("outdoors_nature", "Lake", "water_edge picnic restroom"),
        p("outdoors_nature", "River", "water_edge path_surface shade"),
        p("outdoors_nature", "Island", "ferry_access shelter water_refill"),
        p("outdoors_nature", "Woods/forest", "trail_marking path_surface shelter"),
        p("outdoors_nature", "Mountain peak", "incline trail_marking shelter"),
        p("outdoors_nature", "Scenic spot", "view_access seating shade"),
        // Viewpoint and overlook are alternative names for the same viewing stop.
        p("outdoors_nature", "Viewpoint|Overlook", "view_access path_surface seating"),
        p("outdoors_nature", "Waterfall", "waterfall_view path_surface incline"),
        p("outdoors_nature", "Hot spring", "hot_spring changing admission"),
        p("outdoors_nature", "Cave", "cave path_surface booking"),
        p("outdoors_nature", "Nature preserve", "trail_marking wildlife_viewing leash"),
        p("outdoors_nature", "Wildlife refuge", "wildlife_viewing path_surface shade"),
        p("outdoors_nature", "Wildlife park", "wildlife_viewing animal_paths admission"),
        p("outdoors_nature", "Botanical garden", "garden_labels path_surface shade"),
        p("outdoors_nature", "Garden", "seating shade path_surface"),
        p("outdoors_nature", "Picnic area", "picnic shade restroom"),
        p("outdoors_nature", "Dog park", "fenced leash water_refill"),
        p("outdoors_nature", "Playground", "playground_age fenced shade"),
        p("outdoors_nature", "Campground", "camp_booking camp_toilet camp_surface"),
        p("outdoors_nature", "RV park", "camp_power camp_toilet camp_booking"),
        p("outdoors_nature", "Dispersed camping", "camp_toilet camp_surface offroad"),
        // Accommodation questions stay consistent when the same type is saved
        // under Outdoors or Stays; no public-bathroom claim for a private cabin.
        p("outdoors_nature", "Cabin", "everyday_room_cooling everyday_kitchen everyday_water"),
        p("outdoors_nature", "Cottage", "everyday_kitchen everyday_room_cooling everyday_parking"),
        p("outdoors_nature", "Marina", "boat_access restroom arrival_parking"),
        p("outdoors_nature", "Fishing pier", "fishing_pier_setup seating shade"),
        p("outdoors_nature", "Fishing pond", "fishing_gear fishing_setup seating"),
        p("outdoors_nature", "Fishing charter", "fishing_gear booking restroom"),
        p("outdoors_nature", "Ski resort", "ski_levels ski_rental ride_storage"),
        p("outdoors_nature", "Cycling park", "bike_trails water_refill trail_marking"),
        p("outdoors_nature", "Skate park", "skate_features activity_lights water_refill"),
        p("outdoors_nature", "Off-roading area", "offroad trail_marking shelter"),
        p("outdoors_nature", "Adventure sports", "adventure_guidance equipment booking"),

        p("things_to_do", "Tourist attraction", "admission visit_time step_free"),
        p("things_to_do", "Landmark", "interpretation view_access visit_time"),
        // Historical place/landmark differ in naming, not visitor logistics.
        p("things_to_do", "Historical place|Historical landmark", "interpretation guided_tour step_free"),
        p("things_to_do", "Monument", "interpretation view_access seating"),
        p("things_to_do", "Sculpture", "interpretation photography step_free"),
        p("things_to_do", "Fountain", "seating shade photography"),
        p("things_to_do", "Castle", "guided_tour incline admission"),
        p("things_to_do", "Plaza|Town square", "seating shade restroom"),
        p("things_to_do", "Visitor center", "visitor_info restroom step_free"),
        p("things_to_do", "Museum", "exhibits visit_time admission"),
        p("things_to_do", "Art museum", "exhibits photography seating"),
        p("things_to_do", "History museum", "interpretation guided_tour visit_time"),
        p("things_to_do", "Art gallery", "exhibits photography admission"),
        p("things_to_do", "Art studio", "art_classes equipment booking"),
        p("things_to_do", "Cultural landmark", "interpretation guided_tour photography"),
        p("things_to_do", "Cultural center", "art_classes visitor_info admission"),
        p("things_to_do", "Theater|Performing arts theater", "sightlines show_seating step_free"),
        p("things_to_do", "Concert hall|Philharmonic hall", "acoustics show_seating coat_storage"),
        p("things_to_do", "Opera house", "sightlines acoustics coat_storage"),
        p("things_to_do", "Amphitheater", "sightlines shade show_seating"),
        p("things_to_do", "Auditorium", "acoustics sightlines step_free"),
        p("things_to_do", "Movie theater", "screen_comfort sightlines cinema_snacks"),
        p("things_to_do", "Planetarium", "show_seating admission visit_time"),
        p("things_to_do", "Observation deck", "view_indoor waiting view_access"),
        p("things_to_do", "Aquarium", "hands_on animal_paths admission"),
        p("things_to_do", "Zoo", "animal_paths shade restroom"),
        p("things_to_do", "Amusement park", "ride_queues ride_storage ride_restrictions"),
        p("things_to_do", "Water park", "ride_storage changing ride_restrictions"),
        p("things_to_do", "Ferris wheel", "ride_queues ride_cabin admission"),
        p("things_to_do", "Roller coaster", "ride_queues ride_storage ride_restrictions"),
        p("things_to_do", "Arcade", "game_payment games noise"),
        p("things_to_do", "Bowling", "booking equipment game_payment"),
        p("things_to_do", "Mini golf", "game_payment shade equipment"),
        p("things_to_do", "Billiards", "games game_payment booking"),
        p("things_to_do", "Darts", "equipment games group_tables"),
        p("things_to_do", "Axe throwing", "instruction equipment booking"),
        p("things_to_do", "Board game lounge", "board_games game_payment food_at_bar"),
        p("things_to_do", "Go-karting", "ride_restrictions equipment ride_queues"),
        p("things_to_do", "Paintball", "equipment instruction changing"),
        p("things_to_do", "Indoor playground", "indoor_play seating restroom"),
        p("things_to_do", "Event venue", "event_layout event_food step_free"),
        p("things_to_do", "Convention center", "everyday_wayfinding everyday_charging step_free"),
        p("things_to_do", "Banquet hall", "event_food group_tables step_free"),
        p("things_to_do", "Wedding venue", "event_layout event_food outdoor_seating"),
        p("things_to_do", "Community center", "visitor_info event_layout step_free"),
        p("things_to_do", "Internet cafe", "wifi outlets noise"),
        p("things_to_do", "Dance hall", "dancing group_instruction changing"),
        p("things_to_do", "Barbecue area", "barbecue_setup picnic shade"),

        p("wellness_fitness", "Gym", "fitness_dropin gym_equipment changing"),
        // Provider "fitness center" does not establish that classes exist.
        // Treat this broad label as equivalent to Gym, not a coached studio.
        p("wellness_fitness", "Fitness center", "fitness_dropin gym_equipment changing"),
        p("wellness_fitness", "Yoga studio", "yoga_style equipment class_size"),
        p("wellness_fitness", "Pilates studio", "pilates_format pilates_intro class_size"),
        p("wellness_fitness", "CrossFit gym", "crossfit_scaling crossfit_format fitness_dropin"),
        p("wellness_fitness", "Functional fitness studio", "functional_format coaching class_size"),
        p("wellness_fitness", "Wellness studio", "class_size equipment changing_privacy"),
        p("wellness_fitness", "Wellness center", "treatment_booking changing_privacy step_free"),
        p("wellness_fitness", "Sports club", "fitness_dropin court_booking changing"),
        p("wellness_fitness", "Sports complex", "court_booking changing visitor_info"),
        p("wellness_fitness", "Sports coaching", "coaching group_instruction equipment"),
        p("wellness_fitness", "Sports school", "group_instruction instruction equipment"),
        p("wellness_fitness", "Athletic field", "field_surface activity_lights restroom"),
        p("wellness_fitness", "Swimming pool", "pool_use pool_setting changing"),
        p("wellness_fitness", "Tennis court", "tennis_surface court_booking court_lights"),
        p("wellness_fitness", "Golf course", "golf golf_hire booking"),
        p("wellness_fitness", "Indoor golf", "golf_simulator golf_hire booking"),
        p("wellness_fitness", "Ice skating rink", "ice_sessions equipment ride_storage"),
        p("wellness_fitness", "Volleyball court", "volleyball_surface volleyball_net court_booking"),
        p("wellness_fitness", "Soccer field", "field_surface field_goals activity_lights"),
        p("wellness_fitness", "Basketball court", "basketball court_booking court_lights"),
        p("wellness_fitness", "Pickleball court", "pickleball_lines court_booking court_lights"),
        p("wellness_fitness", "Spa", "treatment_booking changing_privacy sauna"),
        p("wellness_fitness", "Massage", "massage privacy treatment_booking"),
        p("wellness_fitness", "Massage spa", "massage changing_privacy treatment_booking"),
        p("wellness_fitness", "Sauna", "sauna changing_privacy booking"),
        p("wellness_fitness", "Chiropractor", "treatment_booking treatment_info privacy"),
        // Care questions cover facility logistics only; never diagnoses, medical
        // effectiveness or a person's reason for visiting. Equivalent care
        // labels intentionally share practical arrival/appointment questions.
        p("wellness_fitness", "Dentist|Dental clinic", "treatment_booking treatment_info step_free"),
        p("wellness_fitness", "Optometrist", "eye_shop treatment_booking step_free"),
        p("wellness_fitness", "Ophthalmologist", "treatment_booking treatment_info step_free"),
        p("wellness_fitness", "Eye care center", "eye_shop treatment_booking waiting"),
        p("wellness_fitness", "Doctor|Dermatologist", "treatment_booking privacy step_free"),
        p("wellness_fitness", "Pediatrician", "waiting everyday_baby_changing step_free"),
        p("wellness_fitness", "Urgent care", "waiting treatment_booking arrival_parking"),
        p("wellness_fitness", "Medical clinic", "treatment_booking waiting step_free"),
        p("wellness_fitness", "Medical center", "visitor_info arrival_parking step_free"),
        p("wellness_fitness", "Hospital", "visitor_info arrival_parking restroom"),
        p("wellness_fitness", "Medical lab", "lab_booking treatment_info waiting"),
        p("wellness_fitness", "Pharmacy|Drugstore", "pharmacy waiting step_free"),
        p("wellness_fitness", "Physiotherapist|Physical therapy", "rehab_space privacy step_free"),
        p("wellness_fitness", "Foot care|Podiatrist", "treatment_booking privacy step_free"),
        p("wellness_fitness", "Veterinary care", "vet_wait treatment_booking arrival_parking"),
        p("wellness_fitness", "Mental health/therapy", "privacy treatment_booking step_free"),
        p("wellness_fitness", "Retreat", "retreat dietary_menu step_free"),

        p("place", "Place", "step_free seating restroom")
    ]

    private static func p(_ category: String, _ subtypes: String, _ questions: String) -> PlaceCheckInQuestionProfile {
        PlaceCheckInQuestionProfile(
            categoryID: category,
            subcategories: subtypes.components(separatedBy: "|"),
            questionIDs: questions.components(separatedBy: " ")
        )
    }
}
