import Foundation

extension PlaceCheckInQuestionCatalog {
    static let everydayQuestions: [PlaceCheckInQuestion] = [
        everydayQuestion("product_testers", "Testers and samples", "Testers or samples available?", ["Testers", "Samples to take", "Both", "Not offered"], ["Testers": ["product testers"], "Samples to take": ["product samples"], "Both": ["product testers", "product samples"]]),
        everydayQuestion("schedule", "Service timing", "Did the service start on time?", ["On time", "New time agreed", "Delayed without an update"], ["On time": ["service on time on visit"]]),
        everydayQuestion("atm_fee", "Withdrawal fee", "Was the withdrawal fee clear?", ["Fee displayed", "No fee charged", "Not clear"], ["Fee displayed": ["withdrawal fee displayed"], "No fee charged": ["fee free withdrawal on visit"]]),
        everydayQuestion("cash_withdrawal", "Cash machine on this visit", "Could you withdraw cash?", ["Yes", "Machine unavailable", "Transaction did not complete"], ["Yes": ["cash withdrawal worked on visit"]]),
        everydayQuestion("bike_availability", "Bikes on this visit", "Bikes available when you arrived?", ["Yes", "Waited for one", "None available"], ["Yes": ["bikes available on visit"], "Waited for one": ["bike available after waiting"]]),
        everydayQuestion("baby_changing", "Baby changing", "Baby-changing table?", ["Yes", "Only in some toilets", "None found"], ["Yes": ["baby changing table"], "Only in some toilets": ["baby changing in selected toilets"]]),
        everydayQuestion("parking_surface", "Parking surface", "What was the parking surface?", ["Paved", "Gravel", "Grass or dirt", "Mixed"], ["Paved": ["paved parking"], "Gravel": ["gravel parking"], "Grass or dirt": ["unpaved parking"]]),
        everydayQuestion("payment", "Payment", "Card, cash or app?", ["Card or cash", "Card only", "Cash only", "App required", "No charge"], ["Card or cash": ["card payment", "cash accepted"], "Card only": ["card payment"], "Cash only": ["cash only"], "App required": ["app payment"], "No charge": ["no charge on visit"]]),
        everydayQuestion("prices", "Prices", "Clear prices before paying?", ["Clearly displayed", "Explained on request", "Unclear"], ["Clearly displayed": ["clear prices"]]),
        everydayQuestion("browsing", "Browsing space", "How much room was there to browse?", ["Spacious", "Comfortable", "Tight"], ["Spacious": ["spacious browsing"], "Comfortable": ["comfortable browsing"]]),
        everydayQuestion("staff_help", "Staff help", "Help choosing available?", ["Readily available", "Had to ask or wait", "No help available"], ["Readily available": ["choosing help available"]]),
        everydayQuestion("fitting", "Trying things on", "Somewhere to try things on?", ["Fitting room", "Seating or mirror only", "No fitting area"], ["Fitting room": ["fitting rooms"], "Seating or mirror only": ["trying on area"]]),
        everydayQuestion("pickup", "Collection", "How did collection work?", ["Walk-up counter", "Collection time arranged", "Self-service pickup", "Delivery only"], ["Walk-up counter": ["collection counter"], "Collection time arranged": ["scheduled pickup"], "Self-service pickup": ["self service pickup"], "Delivery only": ["delivery service"]]),
        everydayQuestion("loading", "Loading", "Space to load or unload?", ["Dedicated loading area", "Nearby parking", "No convenient spot"], ["Dedicated loading area": ["loading area"], "Nearby parking": ["nearby parking"]]),
        everydayQuestion("parking", "Parking", "Where could you park?", ["On site", "Street nearby", "Paid parking nearby", "None found"], ["On site": ["onsite parking"], "Street nearby": ["street parking"], "Paid parking nearby": ["paid parking"]]),
        everydayQuestion("repair", "Repairs", "Repairs offered?", ["On site", "Sent away", "Not offered"], ["On site": ["onsite repairs"], "Sent away": ["repair service"]]),
        everydayQuestion("refill", "Refill shopping", "Refill your own containers?", ["Yes", "Selected products", "No"], ["Yes": ["refill shopping", "bring containers"], "Selected products": ["selected refills"]]),
        everydayQuestion("gift_wrap", "Gift wrapping", "Gift wrapping offered?", ["Included", "Extra charge", "Not offered"], ["Included": ["gift wrapping included"], "Extra charge": ["paid gift wrapping"]]),
        everydayQuestion("appointment", "Appointments", "Walk-in or appointment?", ["Walked in", "Booked ahead", "Walk-in then later appointment"], ["Walked in": ["walk in visit"], "Booked ahead": ["appointment visit"]]),
        everydayQuestion("turnaround", "Turnaround", "When was the work ready?", ["While I waited", "Same day", "Later collection", "Not completed yet"], ["While I waited": ["while you wait service"], "Same day": ["same day service"], "Later collection": ["collection service"]]),
        everydayQuestion("quote", "Cost estimate", "Cost explained before work began?", ["Written estimate", "Explained verbally", "Not explained"], ["Written estimate": ["written estimate"], "Explained verbally": ["cost explained"]]),
        everydayQuestion("contact", "Booking channel", "How did you book or contact them?", ["Booking website or app", "Phone or message", "In person"], ["Booking website or app": ["online booking"], "Phone or message": ["phone or message booking"]]),
        everydayQuestion("visit_type", "Service location", "Where did the service happen?", ["At their premises", "They came to me", "Remotely"], ["They came to me": ["mobile service"], "Remotely": ["remote service"]]),
        everydayQuestion("dropoff", "Drop-off", "Counter or self-service drop-off?", ["Walk-up desk", "Timed appointment", "Self-service drop-off"], ["Walk-up desk": ["drop off counter"], "Self-service drop-off": ["self service drop off"]]),
        everydayQuestion("self_service", "Service setup", "Self-service or staffed?", ["Self-service", "Staffed", "Both"], ["Self-service": ["self service"], "Staffed": ["staffed service"], "Both": ["self service", "staffed service"]]),
        everydayQuestion("instructions", "Instructions", "Clear instructions?", ["Clear signs or instructions", "Staff explained", "Hard to follow"], ["Clear signs or instructions": ["clear instructions"], "Staff explained": ["staff guidance"]]),
        everydayQuestion("machines", "Machines", "Machines available on arrival?", ["Available immediately", "Short wait", "Long wait or unavailable"], ["Available immediately": ["machines available on visit"]]),
        everydayQuestion("supplies", "Supplies", "Supplies provided?", ["Included", "Available to buy or rent", "Bring your own"], ["Included": ["supplies included"], "Available to buy or rent": ["supplies available"]]),
        everydayQuestion("visitor_access", "Visitor access", "How did visitor entry work?", ["Walked in", "Reception or sign-in", "Appointment or invitation"], ["Walked in": ["walk in visitor access"], "Reception or sign-in": ["visitor reception"], "Appointment or invitation": ["arranged visitor access"]]),
        everydayQuestion("wayfinding", "Finding your way", "Easy to find your way?", ["Clearly signed", "Needed directions", "Difficult to find"], ["Clearly signed": ["clear wayfinding"]]),
        everydayQuestion("waiting_space", "Waiting space", "Somewhere to wait?", ["Seated indoors", "Seated outdoors", "Standing only", "No waiting area"], ["Seated indoors": ["indoor waiting seats"], "Seated outdoors": ["outdoor waiting seats"]]),
        everydayQuestion("shelter", "Weather shelter", "Shelter while waiting?", ["Fully covered", "Partly covered", "Exposed"], ["Fully covered": ["covered waiting area"], "Partly covered": ["partial weather shelter"]]),
        everydayQuestion("luggage", "Luggage storage", "Luggage storage?", ["Staff storage", "Lockers", "Not available"], ["Staff storage": ["luggage storage"], "Lockers": ["luggage lockers"]]),
        everydayQuestion("barrier", "Access area", "Where was the area you used?", ["Before any checks", "After ticket check", "After security"], ["Before any checks": ["outside ticket and security checks"], "After ticket check": ["after ticket checks"], "After security": ["after security"]]),
        everydayQuestion("boarding", "Boarding access", "Step-free route to boarding?", ["Level route", "Lift or ramp", "Steps required"], ["Level route": ["level boarding route"], "Lift or ramp": ["boarding lift or ramp"]]),
        everydayQuestion("charging", "Phone charging", "Phone charging?", ["Outlets", "USB ports", "Both", "None found"], ["Outlets": ["phone charging outlets"], "USB ports": ["usb charging"], "Both": ["phone charging outlets", "usb charging"]]),
        everydayQuestion("charger_use", "Charger on this visit", "Could you start charging?", ["Worked immediately", "Waited then charged", "Could not charge"], ["Worked immediately": ["charger worked on visit"], "Waited then charged": ["charged after waiting"]]),
        everydayQuestion("charging_setup", "Starting a charge", "Card or app to start charging?", ["Tap a payment card", "App or account", "Operator or staff", "Free to connect"], ["Tap a payment card": ["card operated charging"], "App or account": ["app operated charging"], "Free to connect": ["free charging"]]),
        everydayQuestion("bike_pickup", "Bike collection", "How did you collect a bike?", ["App unlock", "Card or kiosk", "Staff handover"], ["App unlock": ["app bike rental"], "Card or kiosk": ["bike rental kiosk"], "Staff handover": ["staffed bike rental"]]),
        everydayQuestion("water", "Water refill", "Water refill?", ["Tap or fountain", "Staff refill", "None found"], ["Tap or fountain": ["water refill"], "Staff refill": ["staff water refill"]]),
        everydayQuestion("showers", "Showers", "Showers available?", ["Included", "Extra charge", "Not available"], ["Included": ["showers included"], "Extra charge": ["paid showers"]]),
        everydayQuestion("laundry", "Laundry", "Laundry available?", ["Self-service", "Staff service", "Not available"], ["Self-service": ["self service laundry"], "Staff service": ["laundry service"]]),
        everydayQuestion("room_noise", "Room noise", "Quiet room when you rested?", ["Quiet", "Some noise", "Disruptive noise"], ["Quiet": ["quiet room on visit"]]),
        everydayQuestion("room_cooling", "Room temperature", "Room temperature controls?", ["Air conditioning", "Heating", "Both", "Fan only", "No controls"], ["Air conditioning": ["room air conditioning"], "Heating": ["room heating"], "Both": ["room air conditioning", "room heating"], "Fan only": ["room fan"]]),
        everydayQuestion("kitchen", "Guest kitchen", "Guest cooking facilities?", ["Private kitchen", "Shared kitchen", "Kettle or microwave only", "None"], ["Private kitchen": ["private kitchen"], "Shared kitchen": ["shared kitchen"], "Kettle or microwave only": ["basic reheating facilities"]]),
        everydayQuestion("breakfast", "Breakfast", "Breakfast included?", ["Included", "Paid option", "Not offered"], ["Included": ["breakfast included"], "Paid option": ["breakfast available"]]),
        everydayQuestion("arrival", "Arrival", "Self check-in or staff welcome?", ["Staff welcomed me", "Self check-in", "Had to arrange arrival"], ["Staff welcomed me": ["staffed arrival"], "Self check-in": ["self check in"]]),
        everydayQuestion("hookups", "Campsite power", "Power at your pitch?", ["Electric hookup", "Shared charging point", "No power"], ["Electric hookup": ["electric campsite hookup"], "Shared charging point": ["shared campsite charging"]]),
        everydayQuestion("pitch_surface", "Pitch surface", "What was your pitch surface?", ["Grass", "Gravel", "Paved", "Mixed or uneven"], ["Grass": ["grass campsite pitch"], "Gravel": ["gravel campsite pitch"], "Paved": ["paved campsite pitch"]]),
        everydayQuestion("privacy", "Sleeping arrangement", "Entire place or shared stay?", ["Entire place", "Private bedroom", "Shared bedroom"], ["Entire place": ["entire place accommodation"], "Private bedroom": ["private guest bedroom"], "Shared bedroom": ["shared guest bedroom"]]),
        everydayQuestion("desk", "Desk space", "Somewhere to work?", ["Desk with chair", "Shared work table", "Small surface only", "None"], ["Desk with chair": ["desk and chair"], "Shared work table": ["shared work table"]]),
        everydayQuestion("quiet_work", "Quiet work", "Quiet place to concentrate?", ["Yes", "Only in certain areas", "No"], ["Yes": ["quiet workspace"], "Only in certain areas": ["quiet areas for concentration"]]),
        everydayQuestion("day_access", "Short visits", "Day or session pass?", ["Day or session pass", "Free guest access", "Membership only"], ["Day or session pass": ["day pass", "session pass"], "Free guest access": ["free guest access"]]),
        everydayQuestion("study_rooms", "Separate rooms", "Separate study or meeting rooms?", ["Bookable rooms", "First come, first served", "No separate rooms"], ["Bookable rooms": ["bookable separate rooms"], "First come, first served": ["walk in separate rooms"]]),
        everydayQuestion("printing", "Printing", "Visitor printing?", ["Yes", "Account or membership needed", "No"], ["Yes": ["visitor printing"], "Account or membership needed": ["member printing"]]),
        everydayQuestion("visitor_guidance", "Visitor guidance", "Clear visitor rules?", ["Signs or information provided", "Staff explained", "Not clear"], ["Signs or information provided": ["visitor information"], "Staff explained": ["staff visitor guidance"]]),
        everydayQuestion("photography", "Photography policy", "What did staff or signs say about photos?", ["Allowed", "Restricted areas or times", "Not allowed"], ["Allowed": ["photography allowed"], "Restricted areas or times": ["restricted photography"]]),
        everydayQuestion("bag_check", "Bags on entry", "Bags checked or stored on entry?", ["Carried inside", "Security check", "Storage required"], ["Carried inside": ["bags carried inside"], "Security check": ["bag security check"], "Storage required": ["bag storage required"]]),
        everydayQuestion("rest_seats", "Resting spots", "Seating without a purchase?", ["Yes", "Limited seats", "No seats found"], ["Yes": ["public seating", "seating without purchase"], "Limited seats": ["limited public seating"]]),
        everydayQuestion("getting_around", "Getting around", "How did you get around?", ["Mostly walked", "Public transport", "Bike", "Car or taxi"], ["Mostly walked": ["explored on foot"], "Public transport": ["explored by public transport"], "Bike": ["explored by bike"]]),
        everydayQuestion("area_pace", "Visit pace", "How long did you spend exploring?", ["Quick stop", "A few hours", "A day", "Several days"], ["Quick stop": ["quick stop visit"], "A few hours": ["few hours exploring"], "A day": ["day exploring"], "Several days": ["several days exploring"]]),
        everydayQuestion("area_highlight", "What stood out", "What stood out where you explored?", ["Food and shops", "Architecture", "Nature", "Culture and history"], ["Food and shops": ["food and shopping visit"], "Architecture": ["architecture visit"], "Nature": ["nature visit"], "Culture and history": ["culture history visit"]]),
        everydayQuestion("walking_surface", "Walking surface", "What was your walking route like?", ["Mostly paved", "Mostly unpaved", "Many steps", "Mixed"], ["Mostly paved": ["paved section walked"], "Mostly unpaved": ["unpaved section walked"], "Many steps": ["steps on route"]]),
        everydayQuestion("crossing", "Crossing", "Marked crossing or bridge?", ["Marked crossing", "Bridge or underpass", "No marked crossing"], ["Marked crossing": ["marked crossing"], "Bridge or underpass": ["pedestrian bridge or underpass"]]),
        everydayQuestion("pedestrian_route", "Walking route", "Walking path separate from traffic?", ["Separate path", "Shared with vehicles", "No walking route"], ["Separate path": ["separate pedestrian path"], "Shared with vehicles": ["shared pedestrian and vehicle route"]]),
        everydayQuestion("tire_air", "Tire air", "Tire air pump?", ["Free pump", "Paid pump", "None found"], ["Free pump": ["free tire air pump"], "Paid pump": ["paid tire air pump"]]),
        everydayQuestion("restroom_fee", "Toilet fee", "Toilet fee?", ["Free", "Paid", "Purchase required"], ["Free": ["free toilet"], "Paid": ["paid toilet"], "Purchase required": ["customers toilet"]]),
        everydayQuestion("handwashing", "Handwashing", "Handwashing facilities?", ["Water and soap", "Water only", "None found"], ["Water and soap": ["handwashing soap"], "Water only": ["handwashing water"]]),
        everydayQuestion("changing", "Changing facilities", "Private or shared changing space?", ["Private cubicles", "Shared changing room", "None"], ["Private cubicles": ["private changing cubicles"], "Shared changing room": ["shared changing room"]]),
        everydayQuestion("lockers", "Lockers", "Lockers available?", ["Included", "Extra charge", "Not available"], ["Included": ["lockers included"], "Extra charge": ["paid lockers"]]),
        everydayQuestion("horse_equipment", "Riding equipment", "Riding equipment provided?", ["Included", "Available to hire", "Bring your own"], ["Included": ["riding equipment included"], "Available to hire": ["riding equipment hire"]])
    ]

    private static func everydayQuestion(
        _ id: String,
        _ label: String,
        _ prompt: String,
        _ options: [String],
        _ searchableAnswers: [String: [String]] = [:]
    ) -> PlaceCheckInQuestion {
        PlaceCheckInQuestion(
            id: keyPrefix + "everyday_" + id,
            displayLabel: label,
            prompt: prompt,
            options: options,
            searchableAnswers: searchableAnswers
        )
    }
}
