begin;

-- Admission rows contain only opaque request identity and lifecycle metadata.
-- Social URLs, captions, provider payloads, and extracted content never enter
-- Postgres. The table is reachable only through the two narrow RPCs below.
create table app.social_import_paid_work_admissions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.profiles(id) on delete cascade,
  client_request_id text not null,
  state text not null default 'in_flight',
  started_at timestamptz not null default clock_timestamp(),
  finished_at timestamptz,
  constraint social_import_paid_work_request_id_check check (
    char_length(client_request_id) between 1 and 160
    and client_request_id ~ '^[A-Za-z0-9._:-]+$'
  ),
  constraint social_import_paid_work_state_check check (
    state in ('in_flight', 'finished', 'expired')
  ),
  constraint social_import_paid_work_finished_at_check check (
    (state = 'in_flight' and finished_at is null)
    or (state in ('finished', 'expired') and finished_at is not null)
  )
);

create index social_import_paid_work_user_started_idx
  on app.social_import_paid_work_admissions(user_id, started_at desc);

create unique index social_import_paid_work_active_request_key
  on app.social_import_paid_work_admissions(user_id, client_request_id)
  where state = 'in_flight';

create unique index social_import_paid_work_finished_request_key
  on app.social_import_paid_work_admissions(user_id, client_request_id)
  where state = 'finished';

alter table app.social_import_paid_work_admissions enable row level security;
revoke all on table app.social_import_paid_work_admissions
  from public, anon, authenticated, service_role;

comment on table app.social_import_paid_work_admissions is
  'Opaque per-user paid social-import admission attempts; never stores URLs, captions, media, or provider payloads.';
comment on column app.social_import_paid_work_admissions.client_request_id is
  'Bounded opaque identifier generated by the app; not a URL or content field.';

create function public.begin_social_import_paid_work(
  input_client_request_id text
)
returns table (
  admitted boolean,
  decision text,
  admission_id uuid
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  viewer_id text := app.current_user_id();
  admission_now timestamptz := pg_catalog.clock_timestamp();
  new_admission_id uuid;
  active_count integer;
  recent_start_count integer;
  paid_import_enabled boolean;
begin
  if viewer_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if input_client_request_id is null
     or pg_catalog.char_length(input_client_request_id) not between 1 and 160
     or input_client_request_id !~ '^[A-Za-z0-9._:-]+$' then
    raise exception 'invalid_client_request_id' using errcode = '22023';
  end if;

  -- This server-side check is the paid-work authority. The app flag is only
  -- presentation. A per-account row wins over the global row, and any missing
  -- or malformed control-plane state fails closed before touching admission
  -- storage or an external provider.
  select coalesce(
    (
      select flag.enabled
      from public.feature_flags as flag
      where flag.key = 'social_import_apify_gemini_v1'
        and flag.user_id = viewer_id
        and flag.value_type = 'boolean'
        and flag.integer_value is null
      limit 1
    ),
    (
      select flag.enabled
      from public.feature_flags as flag
      where flag.key = 'social_import_apify_gemini_v1'
        and flag.user_id is null
        and flag.value_type = 'boolean'
        and flag.integer_value is null
      limit 1
    ),
    false
  )
  into paid_import_enabled;

  if not paid_import_enabled then
    return query select false, 'disabled'::text, null::uuid;
    return;
  end if;

  -- Serialize admission for one account so duplicate, concurrency, and rolling
  -- quota decisions observe one atomic state even under concurrent app calls.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('recme:social-import-paid-work:' || viewer_id, 0)
  );

  -- A paid attempt is bounded below two minutes. Five minutes leaves room for
  -- platform cleanup while ensuring a crashed Edge invocation releases a slot.
  update app.social_import_paid_work_admissions as admission
  set state = 'expired',
      finished_at = admission_now
  where admission.user_id = viewer_id
    and admission.state = 'in_flight'
    and admission.started_at <= admission_now - interval '5 minutes';

  if exists (
    select 1
    from app.social_import_paid_work_admissions as admission
    where admission.user_id = viewer_id
      and admission.client_request_id = input_client_request_id
      and admission.state in ('in_flight', 'finished')
  ) then
    return query select false, 'duplicate'::text, null::uuid;
    return;
  end if;

  select pg_catalog.count(*)::integer
  into active_count
  from app.social_import_paid_work_admissions as admission
  where admission.user_id = viewer_id
    and admission.state = 'in_flight';

  if active_count >= 3 then
    return query select false, 'busy'::text, null::uuid;
    return;
  end if;

  select pg_catalog.count(*)::integer
  into recent_start_count
  from app.social_import_paid_work_admissions as admission
  where admission.user_id = viewer_id
    and admission.started_at > admission_now - interval '24 hours';

  if recent_start_count >= 20 then
    return query select false, 'quota'::text, null::uuid;
    return;
  end if;

  insert into app.social_import_paid_work_admissions (
    user_id,
    client_request_id,
    state,
    started_at,
    finished_at
  ) values (
    viewer_id,
    input_client_request_id,
    'in_flight',
    admission_now,
    null
  )
  returning id into new_admission_id;

  return query select true, 'started'::text, new_admission_id;
end;
$$;

create function public.finish_social_import_paid_work(
  input_client_request_id text,
  input_admission_id uuid
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  viewer_id text := app.current_user_id();
  admission_now timestamptz := pg_catalog.clock_timestamp();
  updated_count integer;
begin
  if viewer_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if input_client_request_id is null
     or pg_catalog.char_length(input_client_request_id) not between 1 and 160
     or input_client_request_id !~ '^[A-Za-z0-9._:-]+$'
     or input_admission_id is null then
    raise exception 'invalid_admission_identity' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('recme:social-import-paid-work:' || viewer_id, 0)
  );

  update app.social_import_paid_work_admissions as admission
  set state = 'expired',
      finished_at = admission_now
  where admission.user_id = viewer_id
    and admission.state = 'in_flight'
    and admission.started_at <= admission_now - interval '5 minutes';

  -- A completed request ID remains the durable duplicate marker. If a very
  -- late orphan races a replacement attempt, expire the replacement instead
  -- of creating a second completed marker for the same request.
  if exists (
    select 1
    from app.social_import_paid_work_admissions as completed
    where completed.user_id = viewer_id
      and completed.client_request_id = input_client_request_id
      and completed.state = 'finished'
  ) then
    update app.social_import_paid_work_admissions as admission
    set state = 'expired',
        finished_at = admission_now
    where admission.id = input_admission_id
      and admission.user_id = viewer_id
      and admission.client_request_id = input_client_request_id
      and admission.state = 'in_flight';
    return false;
  end if;

  update app.social_import_paid_work_admissions as admission
  set state = 'finished',
      finished_at = admission_now
  where admission.id = input_admission_id
    and admission.user_id = viewer_id
    and admission.client_request_id = input_client_request_id
    and admission.state = 'in_flight';

  get diagnostics updated_count = row_count;
  return updated_count = 1;
end;
$$;

revoke all on function public.begin_social_import_paid_work(text)
  from public, anon, service_role;
revoke all on function public.finish_social_import_paid_work(text, uuid)
  from public, anon, service_role;
grant execute on function public.begin_social_import_paid_work(text)
  to authenticated;
grant execute on function public.finish_social_import_paid_work(text, uuid)
  to authenticated;

comment on function public.begin_social_import_paid_work(text) is
  'Atomically admits bounded authenticated social-import work; stores only opaque request identity and lifecycle metadata.';
comment on function public.finish_social_import_paid_work(text, uuid) is
  'Best-effort authenticated completion for an admitted social-import attempt; caller ownership is derived from app.current_user_id().';

commit;
